### PR TITLE
optimize:the property bean may not be initialized while reading config value

### LINKED ISSUE #3006: registry，config 使用consul，报错：config operation timeout,cost:5002ms,op:GET,
环境：
Consul v1.8.0
Seata v1.3.0
java 8
spring-cloud: Hoxton.SR7, spring-boot2.3.2.RELEASE, -> consul api:1.4.5
seata-starter:1.3.0 -> io.seata:seata-all:1.3.0
```
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_tx_group
  config:
    type: consul
    consul:
      server-addr: 10.0.3.0:8500
  registry:
    type: consul
    consul:
      cluster: seata
      server-addr: 10.0.3.0:8500
```
说明：
加载开始读seata.config.consul.serverAddr配置读不到, 报超时；过一会serverAddr就读到了。
```
2020-08-12 11:53:33.115  INFO 1300 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-config/dev-inf-auth-service-dev/'}, BootstrapPropertySource {name='bootstrapProperties-config/dev-inf-auth-service/'}, BootstrapPropertySource {name='bootstrapProperties-config/application-dev/'}, BootstrapPropertySource {name='bootstrapProperties-config/application/'}]
2020-08-12 11:53:33.152  INFO 1300 --- [           main] c.h.l.i.auth.AuthApplication             : The following profiles are active: dev
2020-08-12 11:53:34.381  WARN 1300 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2020-08-12 11:53:34.578  INFO 1300 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=28f509ae-57c3-3591-96eb-f0f55fd6db09
2020-08-12 11:53:34.607  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.seata.spring.boot.autoconfigure.SeataAutoConfiguration' of type [io.seata.spring.boot.autoconfigure.SeataAutoConfiguration$$EnhancerBySpringCGLIB$$c46ae576] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:53:34.614  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'springApplicationContextProvider' of type [io.seata.spring.boot.autoconfigure.provider.SpringApplicationContextProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:53:34.644  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'failureHandler' of type [io.seata.tm.api.DefaultFailureHandlerImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:53:34.649  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cloud.alibaba.seata-io.seata.spring.boot.autoconfigure.properties.SpringCloudAlibabaConfiguration' of type [io.seata.spring.boot.autoconfigure.properties.SpringCloudAlibabaConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:53:34.651  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'seata-io.seata.spring.boot.autoconfigure.properties.SeataProperties' of type [io.seata.spring.boot.autoconfigure.properties.SeataProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:53:34.652  INFO 1300 --- [           main] i.s.s.b.a.SeataAutoConfiguration         : Automatically configure Seata
2020-08-12 11:53:34.695  INFO 1300 --- [           main] io.seata.config.ConfigurationFactory     : load Configuration:FileConfiguration$$EnhancerByCGLIB$$862af1eb
2020-08-12 11:53:39.907  INFO 1300 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configProperties' of type [io.seata.spring.boot.autoconfigure.properties.config.ConfigProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-08-12 11:57:01.376 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:201405 ms,op:GET,dataId:service.disableGlobalTransaction
2020-08-12 11:57:01.379  INFO 1300 --- [           main] i.s.s.a.GlobalTransactionScanner         : Initializing Global Transaction Clients ... 
2020-08-12 11:57:06.386 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5002 ms,op:GET,dataId:transport.threadFactory.bossThreadPrefix
2020-08-12 11:57:11.388 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5002 ms,op:GET,dataId:transport.threadFactory.workerThreadPrefix
2020-08-12 11:57:16.388 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5000 ms,op:GET,dataId:transport.threadFactory.shareBossWorker
2020-08-12 11:57:21.390 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5002 ms,op:GET,dataId:transport.type
2020-08-12 11:57:26.391 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5001 ms,op:GET,dataId:transport.threadFactory.workerThreadSize
2020-08-12 11:57:31.394 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5001 ms,op:GET,dataId:transport.server
2020-08-12 11:57:36.407 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5003 ms,op:GET,dataId:transport.heartbeat
2020-08-12 11:57:41.409 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5002 ms,op:GET,dataId:transport.enableClientBatchSendRequest
2020-08-12 11:57:46.417 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5000 ms,op:GET,dataId:transport.threadFactory.clientSelectorThreadSize
2020-08-12 11:57:51.423 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5001 ms,op:GET,dataId:transport.threadFactory.clientSelectorThreadPrefix
2020-08-12 11:57:56.480 ERROR 1300 --- [           main] io.seata.config.ConfigFuture             : config operation timeout,cost:5002 ms,op:GET,dataId:transport.threadFactory.clientWorkerThreadPrefix

```

### PR DESCRIPTION
**Pull request by xingfudeshi**
### Ⅰ. Describe what this PR did
The property bean may not be initialized while reading config value,so it will cause timeout problem while connecting registry center.like Consul.This PR did a optimization for the problem.

### Ⅱ. Does this pull request fix one issue?

fixes #3006

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Unit test provided.

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by wangliang181230** [comment]
I think it's better to get the configuration directly from the `Environment` in the springboot project.

**Comment by xingfudeshi** [comment]
> I think it's better to get the configuration directly from the `Environment` in the springboot project.
What if the environment variables of Seata conflict with those of other software?

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Comment by wangliang181230** [comment]
> 
> 
> > I think it's better to get the configuration directly from the `Environment` in the springboot project.
> 
> What if the environment variables of Seata conflict with those of other software?

If configuration conflict is considered, all components integrated with springboot will have a headache. Therefore, this issue is generally not considered.

**Pull request merged**
