### PR TITLE
bugfix: the GlobalTransactional annotation npe issue.

### LINKED ISSUE #5434: Could not get the annotation @GlobalTransactional
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
could not get the annotation @GlobalTransactional

### Ⅱ. Describe what happened
image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

### PR DESCRIPTION
**Pull request by sunrui1225**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
fix the GlobalTransactional nullpointerexception issue.

### Ⅱ. Does this pull request fix one issue?

fixes #5434

### CODE REVIEW

**Review by jasondeng1997 — APPROVED** [review]

**Comment by slievrly** [comment]
any issue related ?

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by a364176773** [comment]
> any issue related ?

spring xml方式声明的bean，在进切面的时候method读到的是接口类，而不是实现类，导致注解加到实现类上后，进切面读不到注解，而@service这类注解创建的bean就不会

**Review by l81893521 — APPROVED** [review]
LGTM

**Pull request merged**
