### PR TITLE
optimize: optimize script and add script usage demo.

### PR DESCRIPTION
**Pull request by objcoding**
### Ⅰ. Describe what this PR did
1.optimize script parameter input;
2.add script usage demo;
3.fix create temp log error;
4.remove parameter warning.
5.add group and namespace in nacos script

### CODE REVIEW

**Comment by a364176773** [comment]
nacos SGTM

**Comment by xingfudeshi** [comment]
Redis registry just added three items:
password = ""
cluster = "default"
timeout = "0"

**Comment by xingfudeshi** [comment]
Please add the following new config items.
password = ""
cluster = "default"
timeout = "0"

**Comment by dstiers-1109** [comment]
Pull

**Comment by xingfudeshi** [comment]
@objcoding

**Comment by slievrly** [comment]
> Please add the following new config items.
> password = ""
> cluster = "default"
> timeout = "0"

script synchronization for redis is not covered here.

**Pull request merged**
