### PR TITLE
optimize: timing to get the system time

### PR DESCRIPTION
**Pull request by litianyu1992**

### CODE REVIEW

**Comment by slievrly** [comment]
@litianyu1992 What is the purpose of this PR?

**Comment by litianyu1992** [comment]
> @litianyu1992 What is the purpose of this PR?

印象中在并发量大的情况下，原方式会卡顿

**Comment by litianyu1992** [comment]
> @litianyu1992 What is the purpose of this PR?

印象中，原方式在并发量较大时会有卡顿

**Comment by slievrly** [comment]
> > @litianyu1992 What is the purpose of this PR?
> 
> 印象中，原方式在并发量较大时会有卡顿

Is the slow performance due to metrics?

**Comment by slievrly** [comment]
PMD failure
image

**Pull request closed without merging**
