### PR TITLE
optimize: support jmx port in seata

### LINKED ISSUE #5269: support jmx port for seata-server.sh
## Why you need it?
 Is your feature request related to a problem? Please describe in details
方便jvm相关的exporter或jconsole采集线程数，gc次数等metric数据，应该开放jmx port的设置

```
JMX_PORT=$JMX_PORT
JMX_OPTS=$JMX_OPTS
if [ -z "$JMX_OPTS" ]; then
  JMX_OPTS=" -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false "
fi

if [ -z "$JMX_PORT" ]; then
  JMX_OPTS=" $JMX_OPTS -Dcom.sun.management.jmxremote.port=${JMX_PORT:="10055"} -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT:="10055"} "
fi
```

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by leizhiyuan**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?
fixes #5269

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

image

### Ⅳ. Describe how to verify it

1. `export JMX_ENABLE=true`
2.  run in local machine, check the opts

### CODE REVIEW

**Comment by leizhiyuan** [comment]
sync https://github.com/seata/seata/pull/5938 to develop branch

**Review by funky-eyes — COMMENTED** [review]
You also need to register the githubid in develop.md

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
