### PR TITLE
[release]: release for 1.4.0

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

[vote]: vote for release 1.4.0

### CODE REVIEW

**Comment by a364176773** [comment]
+1 binding.

commit/rollback:
at+db case OK
at-file case OK
at-redis case OK

**Review by l81893521 — COMMENTED** [review]
This sql in Oracle and postgrel would cause NullPointerException
```
oracleAccountJdbcTemplate.update("update account_tbl set money = money - ? where user_id = ?;update account_tbl set money = money - ? where user_id = ?;",new Object[] {money, userId, money, userId});
```

**Comment by long187** [comment]
+1 binding.

commit/rollback:
tcc case OK
saga case OK

**Comment by caohdgege** [comment]
+1 non-binding.
mysql commit/rollback:
AT case: ok
pg multi sql rollback/commit:
AT case: ok

**Comment by caohdgege** [comment]
This sql would cause ClassCastException
```sql
delete from tb where aa=1 limit ?
```

```sql
update tb set address='fdsfd' where aa=1 limit ?
```

**Review by l81893521 — APPROVED** [review]
+1 binding. Tested SQL below:

MYSQL
```
int primaryKey = new Random().nextInt(999999);

KeyHolder keyHolder = new GeneratedKeyHolder();
jdbcTemplate.update(con ->  {
    PreparedStatement preparedStatement = con.prepareStatement("insert ignore into account_tbl(user_id, money, information) values (?, ?, ?)");
    int i = 1;
    preparedStatement.setString(i++, userId);
    preparedStatement.setInt(i++, money);
    preparedStatement.setString(i++, "a");
    return preparedStatement;
}, keyHolder);
log.info("key holder size: {}", keyHolder.getKeyList().size());
jdbcTemplate.update("replace into account_tbl(user_id, money, information, create_time) values (?, ?, ?, now())", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())", primaryKey++, userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(USER_ID, money, information, create_time) values (?, ?, ?, now())", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?)", money, "hello world".getBytes(), userId);
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information) values (?, ?, ?, ?)", primaryKey, userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information) values (null, ?, ?, ?)", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into `account_tbl`(user_id, money, information) values (?, ?, ?)", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into seata.account_tbl(user_id, money, information) values (?, ?, ?)", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into seata.`account_tbl`(user_id, money, information) values (?, ?, ?)", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into `seata`.`account_tbl`(user_id, money, information) values (?, ?, ?)", userId, money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl_multi_pk(user_id, sex, money) values (?, ?, ?)", userId, 1, money);
jdbcTemplate.update("insert into account_tbl_multi_pk(USER_ID, sex, money) values (?, ?, ?)", userId, 1, money);
//batch
jdbcTemplate.update("insert into account_tbl(money, create_time, information, user_id) values (?, now(), ?, ?), (?, now(), ?, ?)", money, "hello world".getBytes(), primaryKey++, money, "hello world".getBytes(), primaryKey++);
jdbcTemplate.update("insert into account_tbl(money, create_time, information, user_id, id) values (?, now(), ?, ?, ?), (?, now(), ?, ?, ?)", money, "hello world".getBytes(), "U100009", primaryKey++, money, "hello world".getBytes(), "U100009", primaryKey++);
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?), (now(), ?, ?, ?)", money, "hello world".getBytes(), "U100009", money, "hello world".getBytes(), "U100009");
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id, id) values (now(), ?, ?, ?, ?), (now(), ?, ?, ?, ?)", money, "hello world".getBytes(), "U100009", primaryKey++, money, "hello world".getBytes(), "U100009", primaryKey++);
jdbcTemplate.batchUpdate("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?)", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        String userId = "U100009";
        ps.setInt(1, money);
        ps.setString(2, userId);
        ps.setBytes(3, "hello world".getBytes());
    }

    @Override
    public int getBatchSize() {
        return 2;
    }
});

jdbcTemplate.update("delete from account_tbl where user_id = ?", userId);
jdbcTemplate.update("delete from `account_tbl` where user_id = ?", userId);
jdbcTemplate.update("delete from seata.account_tbl where user_id = ?", userId);
jdbcTemplate.update("delete from seata.`account_tbl` where user_id = ?", userId);
//order by
jdbcTemplate.update("delete from account_tbl where user_id = ? order by user_id", userId);
jdbcTemplate.update("delete from account_tbl where user_id = ? order by user_id desc", userId);
jdbcTemplate.update("delete from account_tbl where user_id = ? order by user_id asc", userId);
//limit
jdbcTemplate.update("delete from account_tbl where user_id = ? limit 1", userId);
//order by + limit
jdbcTemplate.update("delete from account_tbl where user_id = ? order by user_id limit 1", userId);
jdbcTemplate.update("delete from account_tbl where user_id = ? order by user_id desc limit 1", userId);
//in
jdbcTemplate.update("delete from account_tbl where user_id in (?)", userId);
//between
jdbcTemplate.update("delete from account_tbl where user_id between ? and ?", userId, userId);
//multi pk
jdbcTemplate.update("delete from account_tbl_multi_pk where user_id = ?", userId);

jdbcTemplate.update("update account_tbl set money = money - ?, sex = 1 where user_id = ?", new Object[] {money, userId});
jdbcTemplate.update("update `account_tbl` set money = money - ? where user_id = ?", new Object[] {money, userId});
jdbcTemplate.update("update seata.account_tbl set money = money - ? where user_id = ?", new Object[] {money, userId});
jdbcTemplate.update("update seata.`account_tbl` set money = money - ? where user_id = ?", new Object[] {money, userId});
jdbcTemplate.update("update seata.`account_tbl` set money = money - ? where user_id in (?, ?)", new Object[] {money, "U100002", "U100003"});
jdbcTemplate.update("update seata.`account_tbl` set money = money - ? where user_id in (?, ?, ?)", new Object[] {money, "U100002", "U100003", "U100004"});
jdbcTemplate.update("update seata.`account_tbl` set money = money - ? where user_id in (?, ?)", new Object[] {money, "U100002", "U100004"});
//in
jdbcTemplate.update("update account_tbl set money = money - ? where user_id in (?)", new Object[] {money, userId});
jdbcTemplate.update("update account_tbl set money = money - \" + money + \" where user_id in ('\" + userId + \"')");
//between
jdbcTemplate.update("update account_tbl set money = money - ? where user_id between ? and ?", new Object[] {money, userId, userId});
jdbcTemplate.update("update account_tbl set money = money - " + money + " where user_id between '" + userId + "' and '" + userId + "'");
//exist
jdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = ?)", money, userId);
jdbcTemplate.update("update account_tbl a set money = money - " + money + " where exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = '" + userId + "')");
//not exist
jdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where not exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = ?)", money, userId);
jdbcTemplate.update("update account_tbl a set money = money - " + money + " where not exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = '" + userId + "')");
//multi pk
jdbcTemplate.update("update account_tbl_multi_pk set money = money - ?, sex = 1 where user_id = ? or user_id = ?", new Object[] {money, userId, "U100003"});
//batch
jdbcTemplate.update("update seata.`account_tbl` set money = money - ? where user_id = ?;update seata.`account_tbl` set money = money - ? where user_id = ?;",
        new Object[] {money, userId, money, userId});
jdbcTemplate.batchUpdate(
        "update account_tbl set money = money - " + money + ", sex = 1 where user_id = \"" + userId + "\"",
        "update account_tbl set money = money - " + money + ", sex = 1 where user_id = \"" + userId + "\"");
jdbcTemplate.batchUpdate("update account_tbl set money = money - ?, sex = 1 where user_id = ?", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        ps.setInt(1, money);
        ps.setString(2, userId);
    }
    @Override
    public int getBatchSize() {
        return 2;
    }
});
//batch with multi pk
jdbcTemplate.batchUpdate("update account_tbl_multi_pk set money = money - ?, sex = 1 where user_id = ?", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        ps.setInt(1, money);
        ps.setString(2, userId);
    }

    @Override
    public int getBatchSize() {
        return 2;
    }
});

jdbcTemplate.queryForList("select * from account_tbl where id = ? for update", id);
jdbcTemplate.queryForList("select * from `account_tbl` where id = ? for update", id);
jdbcTemplate.queryForList("select * from seata.account_tbl where id = ? for update", id);
jdbcTemplate.queryForList("select * from seata.`account_tbl` where id = ? for update", id);
//in
jdbcTemplate.queryForList("select * from account_tbl where id in (?) for update", id);
//between
jdbcTemplate.queryForList("select * from account_tbl where id between ? and ? for update", id, id);
//multi pk
jdbcTemplate.queryForList("select * from account_tbl_multi_pk where id = ? for update", id);

```
ORACLE
```
int primaryKey = new Random().nextInt(999999);

KeyHolder keyHolder = new GeneratedKeyHolder();
oracleAccountJdbcTemplate.update(con ->  {
    PreparedStatement preparedStatement = con.prepareStatement("insert into account_tbl(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)");
    int i = 1;
    preparedStatement.setString(i++, userId);
    preparedStatement.setInt(i++, money);
    preparedStatement.setString(i++, "a");
    preparedStatement.setString(i++, "a");
    return preparedStatement;
}, keyHolder);
log.info("key holder size: {}", keyHolder.getKeyList().size());

oracleAccountJdbcTemplate.update("insert into account_tbl(id, user_id, money, information, description) values (?, ?, ?, ?, ?)", primaryKey++, userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into account_tbl(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into \"ACCOUNT_TBL\"(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into test.account_tbl(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into test.\"ACCOUNT_TBL\"(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into \"test\".account_tbl(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");
oracleAccountJdbcTemplate.update("insert into \"test\".\"ACCOUNT_TBL\"(id, user_id, money, information, description) values (account_tbl_seq.nextval, ?, ?, ?, ?)", userId, money, "a", "a");

oracleAccountJdbcTemplate.update("delete from account_tbl where user_id = ?", userId);
oracleAccountJdbcTemplate.update("delete from \"ACCOUNT_TBL\" where user_id = ?", userId);
oracleAccountJdbcTemplate.update("delete from test.account_tbl where user_id = ?", userId);
oracleAccountJdbcTemplate.update("delete from test.\"ACCOUNT_TBL\" where user_id = ?", userId);
//in
oracleAccountJdbcTemplate.update("delete from account_tbl where user_id in (?)", userId);
//between
oracleAccountJdbcTemplate.update("delete from account_tbl where user_id between ? and ?", userId, userId);

oracleAccountJdbcTemplate.update("update account_tbl set money = money - ? where user_id = ?", new Object[] {money, userId});
oracleAccountJdbcTemplate.update("update \"ACCOUNT_TBL\" set money = money - ? where user_id = ?", new Object[] {money, userId});
oracleAccountJdbcTemplate.update("update test.account_tbl set money = money - ? where user_id = ?", new Object[] {money, userId});
oracleAccountJdbcTemplate.update("update test.\"ACCOUNT_TBL\" set money = money - ? where user_id = ?", new Object[] {money, userId});
//in
oracleAccountJdbcTemplate.update("update account_tbl set money = money - ? where user_id in (?)", new Object[] {money, userId});
//between
oracleAccountJdbcTemplate.update("update account_tbl set money = money - ? where user_id between ? and ?", new Object[] {money, userId, userId});
//exist
oracleAccountJdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = ?)", money, userId);
//not exist
oracleAccountJdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where not exists (select 1 from order_tbl o where a.user_id = o.user_id and o.user_id = ?)", money, userId);

oracleAccountJdbcTemplate.queryForList("select * from account_tbl where id = ? for update", id);
oracleAccountJdbcTemplate.queryForList("select * from \"ACCOUNT_TBL\" where id = ? for update", id);
oracleAccountJdbcTemplate.queryForList("select * from test.account_tbl where id = ? for update", id);
oracleAccountJdbcTemplate.queryForList("select * from test.\"ACCOUNT_TBL\" where id = ? for update", id);
//in
oracleAccountJdbcTemplate.queryForList("select * from account_tbl where id in (?) for update", id);
//between
oracleAccountJdbcTemplate.queryForList("select * from account_tbl where id between ? and ? for update", id, id);
```
POSTGRE
```
int primaryKey = new Random().nextInt(999999);
KeyHolder keyHolder = new GeneratedKeyHolder();
jdbcTemplate.update(con ->  {
    PreparedStatement preparedStatement = con.prepareStatement("insert into account_tbl(id, user_id, money) values (nextval('\"seata\".account_tbl_id_seq'), ?, ?)");
    int i = 1;
    preparedStatement.setString(i++, userId);
    preparedStatement.setInt(i++, money);
    return preparedStatement;
}, keyHolder);
log.info("key holder size: {}", keyHolder.getKeyList().size());
if (shouldThrowException) {
    jdbcTemplate.update("insert into account_tbl(id, user_id, money) values (9999, trim(both ?), ?)", userId, money);
}

jdbcTemplate.update("insert into account_tbl(id, user_id, money) values (?, trim(both ?), ?)", primaryKey++, userId, money);
jdbcTemplate.update("insert into account_tbl(id, user_id, money) values (nextval('\"seata\".account_tbl_id_seq'), trim(both ?), ?)", userId, money);
jdbcTemplate.update("insert into seata.account_tbl(user_id, money, id) values (trim(both ?), ?, nextval('\"seata\".account_tbl_id_seq'))", userId, money);
jdbcTemplate.update("insert into account_tbl(id, user_id, money) values (default, ?, ?)", userId, money);
//batch
jdbcTemplate.update("insert into account_tbl(id, money, user_id) values (nextval('\"seata\".account_tbl_id_seq'), ?, ?), " +
        "(nextval('\"seata\".account_tbl_id_seq'), ?, ?)", money, userId, money, userId);
jdbcTemplate.update("insert into account_tbl(id, money, user_id) values (default, ?, ?), (default, ?, ?)", money, userId, money, userId);
jdbcTemplate.batchUpdate("insert into account_tbl(id, money, user_id) values (default, ?, ?)", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        String userId = "U100009";
        ps.setInt(1, money);
        ps.setString(2, userId);
    }

    @Override
    public int getBatchSize() {
        return 2;
    }
});

jdbcTemplate.update("delete from account_tbl where user_id = ?", userId);
jdbcTemplate.update("delete from \"account_tbl\" where user_id = ?", userId);
//in
jdbcTemplate.update("delete from account_tbl where user_id in (?)", userId);
//between
jdbcTemplate.update("delete from account_tbl where user_id between ? and ?", userId, userId);

jdbcTemplate.update("update account_tbl set money = money - ? where user_id = ?", new Object[] {money, userId});
jdbcTemplate.update("update \"account_tbl\" set money = money - ? where user_id = ?", new Object[] {money, userId});
//in
jdbcTemplate.update("update account_tbl set money = money - ? where user_id in (?)", new Object[] {money, userId});
//between
jdbcTemplate.update("update account_tbl set money = money - ? where user_id between ? and ?", new Object[] {money, userId, userId});
//batch
jdbcTemplate.batchUpdate("update account_tbl set money = money - " + money + " where user_id = '" + userId + "'", "update account_tbl set money = money - " + money + " where user_id = '" + userId + "'");
jdbcTemplate.batchUpdate("update account_tbl set money = money - ? where user_id = ?", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        ps.setInt(1, money);
        ps.setString(2, userId);
    }
    @Override
    public int getBatchSize() {
        return 2;
    }
});

jdbcTemplate.queryForList("select * from account_tbl where id = ? for update", id);
jdbcTemplate.queryForList("select * from \"account_tbl\" where id = ? for update", id);
//in
jdbcTemplate.queryForList("select * from account_tbl where id in (?) for update", id);
//between
jdbcTemplate.queryForList("select * from account_tbl where id between ? and ? for update", id, id);
if (shouldThrowException) {
    throw new RuntimeException("查询锁失败");
} else {
    log.info("-----------------------------查询锁成功-----------------------------");
}
```

**Comment by slievrly** [comment]
+1 binding
- [x] AT: Postgresql  Dubbo manual Proxy  commit/rollback ;
- [x] AT: MySQL 5.x  Dubbo manual Proxy  commit/rollback ;
- [x] AT: ORACLE 12.c  Dubbo manual Proxy  commit/rollback ;

- [x] AT: MySQL 5.x  SCA auto Proxy commit/rollback ;

**Review by caohdgege — APPROVED** [review]
LGMT

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
