### PR TITLE
release: release 1.2.0

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

vote: vote for release Seata 1.2.0
 at least 3 votes with binding to pass

Please vote accordingly:
- [x] +1 approve
- [x] +0 no opinion
- [x] -1 disapprove with the reason

### CODE REVIEW

**Comment by slievrly** [comment]
+1 binding
- [ ] Dubbo MySQL commit/rollback  file mode
- [ ] Dubbo MySQL commit/rollback  db mode
- [ ] Spring Cloud  MySQL commit/rollback  file mode

**Comment by a364176773** [comment]
+1 non-binding

**Comment by l81893521** [comment]
+1 binding

**Comment by zhongfuhua** [comment]
+1 non-binding

**Comment by xingfudeshi** [comment]
+1 binding

**Comment by objcoding** [comment]
+1 non-binding

**Comment by jsbxyyx** [comment]
+1 binding

**Comment by wxbty** [comment]
+1 non-binding

**Comment by CharmingRabbit** [comment]
+1 non-binding

**Comment by zhangthen** [comment]
+1 binding

**Comment by lightClouds917** [comment]
+1 non-binding

**Comment by long187** [comment]
+1

**Comment by slievrly** [comment]
we have received 7+5 (binding)votes for release 1.2.0.

**Comment by ph3636** [comment]
+1 non-binding

**Pull request merged**
