### PR TITLE
bugfix: wrong keyword order for oracle when creating a table

### PR DESCRIPTION
**Pull request by xssdpgy**
- [x] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
when create table 'lock_table' in Oracle, will report 'ORA-00907: missing right parenthesis'，because the DDL(field:status) has a worong keyword order in oracle, and DB will check it.
image

### CODE REVIEW

**Review by a364176773 — COMMENTED** [review]
https://github.com/seata/seata/tree/develop/changes 请在中英两版develop.md中登记作者信息和pr信息

**Review by jsbxyyx — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
LGTM

**Pull request merged**
