### PR TITLE
Optimizing sqlType actuator based on static factory pattern

### PR DESCRIPTION
**Pull request by pengzhengfa**
Hello, please check

### CODE REVIEW

**Comment by a364176773** [comment]
please resolve ci error

**Comment by pengzhengfa** [comment]
@a364176773  Can you help me? I don't know that very well. I don't seem to have permission to write at present

**Comment by a364176773** [comment]
`Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (validate) on project seata-rm-datasource: Failed during checkstyle execution: There are 3 errors reported by Checkstyle 6.18 with /home/travis/build/seata/seata/style/seata_checkstyle.xml ruleset. `
It looks like the code is unformatted,please use alibaba-p3c Code specification to format code

**Comment by pengzhengfa** [comment]
@a364176773 It's passed the examination. Help me merge. Thank you

**Pull request closed without merging**
