### PR TITLE
bugfix: registration service configuration missing and inconsistent

### PR DESCRIPTION
**Pull request by ph3636**
### Ⅰ. Describe what this PR did
inconsistent Redis and Etcd3 publish and subscribe service
SOFA property name setting error
Nacos and SOFA missing client configuration

### CODE REVIEW

**Comment by a364176773** [comment]
server/src/main/resources/registry.conf are the password and timeout configuration missing in the file? need to add it?

**Comment by slievrly** [comment]
explanation: the local clusterName variable needs to be used here, because the configuration properties of the cluster may not exist on the client side but only on the server side.

**Comment by ph3636** [comment]
> server/src/main/resources/registry.conf are the password and timeout configuration missing in the file? need to add it?

done

**Comment by zjinlei** [comment]
retry ci

**Comment by ph3636** [comment]
inconsistent Redis and Etcd3 publish and subscribe service
SOFA property name setting error
Nacos and SOFA missing client configuration

Found some problems

PTAL @slievrly @a364176773 @zjinlei

**Comment by slievrly** [comment]
> inconsistent Redis and Etcd3 publish and subscribe service
> SOFA property name setting error
> Nacos and SOFA missing client configuration
> 
> Found some problems
> 
> PTAL @slievrly @a364176773 @zjinlei

great found.

**Pull request merged**
