### PR TITLE
feature: spring boot support for custom config and registry type

### LINKED ISSUE #3196: Spring Boot support for custom config and registry type
## Why you need it?
The pull request #1625 introduces a custom config and registry type to help users create their own configuration loading mechanism.

This custom registry type can be used and configured using a `registry.conf` file:
```
registry {
  type = "custom"

  custom {
    name = "MyCustomRegistry"
  }
} 
```

Unfortunately, it cannot currently be configured via `application.properties` when using Spring Boot.

## How it could be?
The custom registry type can be configured in `application.properties` as follow:
```
seata.registry.type=custom
seata.registry.custom.name=MyCustomRegistry
```

### PR DESCRIPTION
**Pull request by JRial95**
### Ⅰ. Describe what this PR did
Add the Spring Boot support for custom config and registry type

### Ⅱ. Does this pull request fix one issue?
Fixes #3196.

### CODE REVIEW

**Comment by JRial95** [comment]
Yes, it works for the custom registry. [Here](https://github.com/JRial95/seata-spring-boot-custom-registry) is a minimal example.
However, I have not tested the custom config.

**Comment by JRial95** [comment]
I have updated my example. The custom config also works.

**Comment by a364176773** [comment]
thx. good job------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jonathan&amp;nbsp;Rial&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月15日(星期四) 晚上11:53
收件人:&nbsp;&quot;seata/seata&quot;<seata@noreply.github.com&gt;;
抄送:&nbsp;&quot;FUNKYE&quot;<364176773@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [seata/seata] feature: spring boot support for custom config and registry type (#3198)

**Comment by a364176773** [comment]
`registry {
  type = "custom"

  custom {
    name = "MyCustomRegistry"
  }
} `

This is possible as long as your dependency is seata-all

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by wangliang181230** [comment]
Please add configuration information to the configuration file in `/script/client`

**Comment by JRial95** [comment]
@wangliang181230 Configuration information added to the configuration file in ```/script/client```

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Pull request merged**
