### PR TITLE
 migrate: Migrate CI provider from Travis CI to Github Actions.

### PR DESCRIPTION
**Pull request by ujjboy**
### Ⅰ. Describe what this PR did

Migrate CI provider from Travis CI to Github Actions. 

ref: https://docs.github.com/cn/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

### CODE REVIEW

**Comment by caohdgege** [comment]
ci的报错修复了，把develop合并到你的分支再推一下？

**Comment by ujjboy** [comment]
这两个用例还是错的
io.seata.integration.http.HttpTest#testPostProviderXID 
io.seata.core.context.RootContextTest#testBind_And_Unbind

**Comment by a364176773** [comment]
> 这两个用例还是错的
> io.seata.integration.http.HttpTest#testPostProviderXID
> io.seata.core.context.RootContextTest#testBind_And_Unbind

https://github.com/seata/seata/pull/3359
这个pr修掉了#testBind_And_Unbind不通过的bug，testPostProviderXID本地跑没有发现有什么异常

**Review by slievrly — COMMENTED** [review]
great job

**Review by slievrly — APPROVED** [review]

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
