### PR TITLE
support: add the max wait configuration for db

### PR DESCRIPTION
**Pull request by a364176773**
### Ⅰ. Describe what this PR did
increase max wait parameter configuration

### Ⅱ. Does this pull request fix one issue?

#2482

### CODE REVIEW

**Comment by lightClouds917** [comment]
add this to the script @a364176773

**Comment by a364176773** [comment]
> add this to the script @a364176773

ok

**Comment by a364176773** [comment]
> add this to the script @a364176773

PTAL

**Comment by lightClouds917** [comment]
LGTM

**Pull request merged**
