### PR TITLE
fix field type is datetime equals fail

### PR DESCRIPTION
**Pull request by jsbxyyx**
fix: #1116

### CODE REVIEW

**Comment by slievrly** [comment]
@jsbxyyx modify your pr title，will be as commit log.

**Comment by ujjboy** [comment]
I think this is not the problem, the reason for #1116 is the `json` serialization loses millisecond precision.

**Comment by jsbxyyx** [comment]
> I think this is not a real solution, the reason for #1116 is the `json` serialization loses millisecond precision.

I also think this is not a good solution. the problem solution requires a serialization method that preserves the type.

**Comment by zhangthen** [comment]
The actual reason is that the serialization protocol(fastjson) used by undo log is not a good one.

**Pull request merged**
