### PR TITLE
bugfix: seata-core dependency transitive conflict in seata-dubbo

### PR DESCRIPTION
**Pull request by AlbumenJ**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

image

Temporally solution:
```xml
        <dependency>
            <groupId>io.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
            <version>${seata.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

### CODE REVIEW

**Comment by slievrly** [comment]
@AlbumenJ  `dubbo-filter-extensions` include `seata-core` dependency. Can we solve this problem if we declare the scope of 'seata-core' as provided?

**Comment by AlbumenJ** [comment]
> @AlbumenJ `dubbo-filter-extensions` include `seata-core` dependency. Can we solve this problem if we declare the scope of 'seata-core' as provided?

Yes. But this requires `dubbo-filter-extensions` release `1.0.2`, and this will take some time.

**Comment by wangliang181230** [comment]
参照这个 PR https://github.com/seata/seata/pull/5219 再改几处吧。

**Comment by AlbumenJ** [comment]
> 参照这个 PR #5219 再改几处吧。

done

**Review by a364176773 — APPROVED** [review]
LGTM @slievrly PTAL

**Review by jsbxyyx — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
LGTM

**Pull request merged**
