### PR TITLE
feature: add benchmark projects

### PR DESCRIPTION
**Pull request by ggndnn**
### Ⅰ. Describe what this PR did
Performance is critical, this PR was opened to encourage and help contributors to do benchmark test and improve performance. Project `seata-benchmark-undolog` is an example of microbenchmark.

### CODE REVIEW

**Comment by leizhiyuan** [comment]
maybe it should be in another project？like the  sample project？

**Comment by lovepoem** [comment]
> maybe it should be in another project？like the sample project？

Agree with you 
Benchmark tests are usually used as performance tests to get benchmark data. Modifications are not frequent, and it's better to be a separate project.

**Comment by ggndnn** [comment]
> > maybe it should be in another project？like the sample project？
> 
> Agree with you
> Benchmark tests are usually used as performance tests to get benchmark data. Modifications are not frequent, and it's better to be a separate project.

I thought about it too, a separate benchmark project. How to add one?

**Comment by slievrly** [comment]
> > > maybe it should be in another project？like the sample project？
> > 
> > 
> > Agree with you
> > Benchmark tests are usually used as performance tests to get benchmark data. Modifications are not frequent, and it's better to be a separate project.
> 
> I thought about it too, a separate benchmark project. How to add one?

https://github.com/seata/seata-benchmark

**Comment by ggndnn** [comment]
Close this PR here and reopen another one [https://github.com/seata/seata-benchmark/pull/1](https://github.com/seata/seata-benchmark/pull/1) in seata-benchmark.

**Pull request closed without merging**
