### PR TITLE
optimize: acquire lock return fail-fast code in redis-pipeline mode.

### PR DESCRIPTION
**Pull request by objcoding**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
When the local transaction and the global transaction are enabled, the branch registration fails to acquire the global lock, the lock holder is in the second-stage rollback, and the branch registration fails to be retried quickly, because the retry with the local transaction does not release the database lock , resulting in a two-phase rollback wait. Therefore, if a global lock is found in the Rollbacking state, the fail-fast code is returned directly.

### Ⅱ. Does this pull request fix one issue?

#4267

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM 补充下1.5.0.md

**Comment by a364176773** [comment]
按标题的意思这个pr应该是个optimize

**Comment by objcoding** [comment]
> 按标题的意思这个pr应该是个optimize

是的，原则上是pr3733的一个优化，因为pr3733并没有打包release版本，还处于develop分支。

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
