### PR TITLE
optimize: remove unused method

### PR DESCRIPTION
**Pull request by l81893521**
### Ⅰ. Describe what this PR did
remove unused method getCreateTableSQL in TableMeta

### Ⅱ. Does this pull request fix one issue?
#1714

### CODE REVIEW

**Comment by l81893521** [comment]
I will add some unit test to increase code coverage later.

**Comment by slievrly** [comment]
@l81893521 Is there a better description of the pr title?

**Comment by xingfudeshi** [comment]
> @l81893521 Is there a better description of the pr title?

remove unused methods?

**Comment by l81893521** [comment]
> @l81893521 Is there a better description of the pr title?

is this ok?

**Comment by l81893521** [comment]
the unit test will be add in #1674

**Pull request merged**
