### PR TITLE
bugfix: output expression incorrectly throws npe

### LINKED ISSUE #4948: saga模式定义ServiceTask的Output表达式错误的话，会出现空指针异常
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
saga模式定义ServiceTask的Output表达式错误的话，会出现空指针异常

### Ⅱ. Describe what happened
output 表达式定义错误。会在记录数据库的时候未设置 GmtEnd 字段。在保存的时候会调用 
`stateInstance.getGmtEnd().getTime())`
出现空指针异常. 
image
应该在 ServiceTaskHandlerInterceptor 的 
image
设置 stateInstance.setGmtEnd(new Date()); 字段。

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 8
- Seata version:  1.4.2
- OS :
- Others:

### PR DESCRIPTION
**Pull request by 1181954449**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
output 表达式错误时，抛出期望的异常。而不是空指针

### Ⅱ. Does this pull request fix one issue?

fixes #4948

### CODE REVIEW

**Review by a364176773 — COMMENTED** [review]
请在 https://github.com/seata/seata/tree/develop/changes 的中英两版develop.md进行此pr的登记,可参照其它人的登记方式,将pr和作者信息进行登记

**Comment by 1181954449** [comment]
已经登记

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Comment by wangliang181230** [comment]
md文件里，贡献者名单里加一下自己的名字吧。

**Pull request merged**
