### PR TITLE
optimized: remove unused code in serializer factory.

### PR DESCRIPTION
**Pull request by l81893521**
### Ⅰ. Describe what this PR did
remove unused code in serializer factory.

### CODE REVIEW

**Review by l81893521 — COMMENTED** [review]
or remove the whole SerializerFactory. User EnhancedServiceLoader.load in the encoder and decoder. Can somebody give me some advice?

**Review by slievrly — COMMENTED** [review]
I think SerializerFactory can indeed be deleted.

**Comment by a364176773** [comment]
> I think SerializerFactory can indeed be deleted.

+1

**Review by slievrly — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Pull request merged**
