### PR TITLE
optimize: The server directory is build by version, and build only when the profile is 'release-seata'

### PR DESCRIPTION
**Pull request by wangliang181230**
### Ⅰ. Describe what this PR did
optimize: The server directory is build by version, and build only when the profile is `release-seata`.
优化：`seata-server`的目录按版本号构建，且仅当`profile`为`release-seata`时才构建。

### 优化后的好处
1. 按版本号构建目录的好处：在不同版本的分支切换并分别构建`seata-server`时，不同版本的jar包不会混淆在一个目录中。
2. `profile=release-seata`才构建的好处：有时候我们只是想重新打包上传到maven私服，但构建server会因为部分文件被占用，导致构建失败从而影响打包上传。

### CODE REVIEW

**Comment by slievrly** [comment]
missing `-Dlogback.color.disable-for-bat=true`

**Comment by wangliang181230** [comment]
> 
> 
> missing `-Dlogback.color.disable-for-bat=true`

I will merge the `develop` branch.

**Comment by wangliang181230** [comment]
> 
> 
> missing `-Dlogback.color.disable-for-bat=true`

done

**Comment by slievrly** [comment]
image

**Review by slievrly — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by l81893521 — APPROVED** [review]
LGTM

**Pull request merged**
