### PR TITLE
bugfix: fix in high version springboot property not resolved

### PR DESCRIPTION
**Pull request by liujunlin5168**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
bugfix: fix in high version springboot property not Standard

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM @wangliang181230 PTAL

**Comment by slievrly** [comment]
#4801

**Comment by slievrly** [comment]
@liujunlin5168 Pls indicate the starting springboot version.

**Review by slievrly — APPROVED** [review]
LGTM

**Review by l81893521 — APPROVED** [review]
LGTM

**Pull request merged**
