### PR TITLE
Add test for MergedWarpMessage

### PR DESCRIPTION
**Pull request by leizhiyuan**
### Ⅰ. Describe what this PR did

only add test case 

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/seata/seata/issues/195

### Ⅳ. Describe how to verify it

test case

### CODE REVIEW

**Comment by leizhiyuan** [comment]
by the way, maybe the class name is a typo? warp or wrap?

**Comment by leizhiyuan** [comment]
> Can you add unit tests for other public methods?

ok

**Comment by slievrly** [comment]
@leizhiyuan https://shimo.im/sheet/7TOkAXkq8FcLon5K/mO2Lt

**Comment by leizhiyuan** [comment]
> @leizhiyuan https://shimo.im/sheet/7TOkAXkq8FcLon5K/mO2Lt

OK

**Pull request merged**
