### PR TITLE
feature：support h2 in AT mode

### LINKED ISSUE #4122: 什么时候支持h2数据库呢？
seata什么时候可以支持h2数据库呢 ？还是说我们需要基于seata-all中自行扩展h2数据库支持？

### PR DESCRIPTION
**Pull request by HongYan789**
Ⅰ. Describe what this PR did
support h2 DataBase

Ⅱ. Does this pull request fix one issue?
fixes #4122

Ⅲ. Why don't you add test cases (unit test/integration test)?
Test cases have been added

Ⅳ. Describe how to verify it

The SQL file is the same as mysql
As follows:
CREATE TABLE `undo_log` (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`branch_id` bigint(20) NOT NULL,
	`xid` varchar(100) NOT NULL,
	`context` varchar(128) NOT NULL,
	`rollback_info` longblob NOT NULL,
	`log_status` int(11) NOT NULL,
	`log_created` datetime NOT NULL,
	`log_modified` datetime NOT NULL,
	`ext` varchar(100) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `ux_undo_log` (`xid`,`branch_id`)
) ;

Ⅴ. Special notes for reviews
See for details ：
H2DeleteExecutorTest.java
H2InsertExecutorTest.java
H2DeleteRecognizerTest.java
H2InsertRecognizerTest.java
H2UpdateRecognizerTest.java

### CODE REVIEW

**Comment by a364176773** [comment]
欢迎你的贡献，请麻烦把你的钉钉号发到我邮箱364176773@qq.com

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4096 参考这个pr的标题和内容说明

**Comment by HongYan789** [comment]
已经按照要求调整标题和内容

**Comment by funky-eyes** [comment]
Due to code conflicts and age, if you are still interested in participating in the community, please resubmit this pr to the 2.x branch after resolving the conflict.
由于代码冲突以及年代久远，如果你还有兴趣参与到社区，请解决完冲突后重新请提交这份pr至2.x分支中

**Pull request closed without merging**
