### PR TITLE
optimize: globalTransactionScanner listener optimize

### LINKED ISSUE #3377: globalTransactionScanner listener optimize
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
when disableGlobalTransaction is true, it means that the global transaction is not currently enabled. At this time, you need to monitor the change of disableGlobalTransaction to initialize the component, and if the initial value of disableGlobalTransaction is false, then there is no need to monitor disableGlobalTransaction
在disableGlobalTransaction为true时，说明目前未开启全局事务，此时需要监听disableGlobalTransaction的变化来初始化组件，而如果disableGlobalTransaction一开始的值为false，那么无需进行监听disableGlobalTransaction

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by lj2018110133**
### Ⅰ. Describe what this PR did
globalTransactionScanner listener optimize

### Ⅱ. Does this pull request fix one issue?

fixes  #3377

### CODE REVIEW

**Comment by slievrly** [comment]
When disableGlobalTransaction = true at startup, why don't you need to listen to configuration changes for on disableGlobalTransaction?

**Comment by slievrly** [comment]
@lj2018110133 merge the latest develop branch code.

**Review by slievrly — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
