### PR TITLE
bugfix: run with jar file and not package third lib into jar file, this.getClass().getClassLoader() will be null

### PR DESCRIPTION
**Pull request by lian88jian**
### Ⅰ. Describe what this PR did
jar运行模式, 当第三方依赖分开打包时, this.getClass().getClassLoader()是null, 会报空指针异常

### Ⅱ. Does this pull request fix one issue?
#3407

### CODE REVIEW

**Comment by a364176773** [comment]
Error:  /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:170:9: 'if' is not followed by whitespace. [WhitespaceAround]
Error:  /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:170:32: '{' is not preceded with whitespace. [WhitespaceAround]
Error:  /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:175: 'array initialization' child has incorrect indentation level 20, expected level should be 16. [Indentation]
Error:  /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:179: 'array initialization' child has incorrect indentation level 20, expected level should be 16. [Indentation]

这几个代码按照阿里p3c代码格式化一下

**Comment by lian88jian** [comment]
> Error: /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:170:9: 'if' is not followed by whitespace. [WhitespaceAround]
> Error: /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:170:32: '{' is not preceded with whitespace. [WhitespaceAround]
> Error: /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:175: 'array initialization' child has incorrect indentation level 20, expected level should be 16. [Indentation]
> Error: /home/runner/work/seata/seata/config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java:179: 'array initialization' child has incorrect indentation level 20, expected level should be 16. [Indentation]
> 
> 这几个代码按照阿里p3c代码格式化一下

好了.

**Review by l81893521 — APPROVED** [review]
LGTM

**Review by jsbxyyx — APPROVED** [review]
LGTM

**Pull request merged**
