### PR TITLE
optimize: optimize the memory footprint of redis mode

### LINKED ISSUE #3526: 不停的fullGc，导致服务无响应
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
dubbo服务的分布式事务，在执行了100多W事务后，每秒大概600左右事务，seata-server开始不停GC，直致无响应

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:
GC日志：
9875.805: [Full GC (Ergonomics)  1923069K->1923069K(2010112K), 1.7326736 secs]
9877.539: [Full GC (Ergonomics)  1923069K->1923069K(2010112K), 1.7196613 secs]
9879.259: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7209864 secs]
9880.980: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7254770 secs]
9882.706: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7320489 secs]
9884.439: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7189184 secs]
9886.158: [Full GC (Allocation Failure)  1923071K->1923071K(2010112K), 1.7227557 secs]
9887.881: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7234524 secs]
9889.605: [Full GC (Allocation Failure)  1923071K->1923071K(2010112K), 1.7238439 secs]
9891.329: [Full GC (Ergonomics)  1923071K->1923069K(2010112K), 1.7250560 secs]
9893.055: [Full GC (Ergonomics)  1923069K->1923069K(2010112K), 1.7183158 secs]
9894.774: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7194053 secs]
9896.493: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7154990 secs]
9898.209: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7193842 secs]
9899.929: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7194376 secs]
9901.649: [Full GC (Allocation Failure)  1923071K->1923071K(2010112K), 1.7215232 secs]
9903.371: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7160572 secs]
9905.087: [Full GC (Allocation Failure)  1923071K->1923071K(2010112K), 1.7215137 secs]
9906.809: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7758575 secs]
9908.586: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.9020872 secs]
9910.488: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7110060 secs]
9912.200: [Full GC (Ergonomics)  1923071K->1923071K(2010112K), 1.7142365 secs]
9913.914: [Full GC (Allocation Failure)  1923071K->1923071K(2010112K), 1.7206138 secs]
9915.635: [Full GC (Ergonomics)  1923071K->1923065K(2010112K), 1.9138982 secs]
9917.550: [Full GC (Ergonomics)  1923068K->1923063K(2010112K), 1.9363447 secs]
9919.487: [Full GC (Ergonomics)  1923065K->1923063K(2010112K), 1.7181851 secs]
9921.205: [Full GC (Ergonomics)  1923065K->1923063K(2010112K), 1.7240425 secs]
9922.930: [Full GC (Ergonomics)  1923065K->1923065K(2010112K), 1.7183898 secs]
9924.649: [Full GC (Ergonomics)  1923065K->1923065K(2010112K), 1.7189530 secs]
9926.368: [Full GC (Ergonomics)  1923067K->1923066K(2010112K), 1.7181834 secs]
9928.087: [Full GC (Ergonomics)  1923066K->1923066K(2010112K), 1.7228224 secs]
9929.810: [Full GC (Ergonomics)  1923069K->1923068K(2010112K), 1.7232653 secs]
9931.534: [Full GC (Ergonomics)  1923071K->1923069K(2010112K), 1.7183493 secs]
9933.253: [Full GC (Ergonomics)  1923071K->1923070K(2010112K), 1.7197703 secs]
9934.973: [Full GC (Ergonomics)  1923071K->1923070K(2010112K), 1.7297920 secs]

server log:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅴ. Anything else we need to know?
内存快照：
Uploading 
![seata-dump1
seata-dump-detail

seata-dump.png…]()

### Ⅵ. Environment:

- JDK version : open-jdk8
- OS : centos 7.2
- Others:

### PR DESCRIPTION
**Pull request by a364176773**
### Ⅱ. Does this pull request fix one issue?

fixes #3526

### CODE REVIEW

**Review by xingfudeshi — APPROVED** [review]
LGTM.

**Comment by a364176773** [comment]
@ph3636 @lightClouds917 PTAL

**Review by ph3636 — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
LGTM,  vote for @ph3636

**Pull request merged**
