### PR TITLE
bugfix: fix loader path in startup scripts

### PR DESCRIPTION
**Pull request by neillee95**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
Following [this doc](https://seata.io/en-us/docs/ops/deploy-server.html) to deloy server directly, server startup failed with command
```shell
sh ./bin/seata-server.sh
```
stack trace as following
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at io.seata.server.ServerApplication.main(ServerApplication.java:30)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more
```
jars in lib are not loaded by spring boot loader. 
In bin/seata-server.sh, [loader path](https://github.com/seata/seata/blob/develop/distribution/bin/seata-server.sh#L130) is relative, it means that server must be startup under bin directory or set LOADER_PATH.
This pr replaces the relative path to absolute path.

### CODE REVIEW

**Review by slievrly — APPROVED** [review]
LGTM

**Comment by slievrly** [comment]
@neillee95 does the bat script have the same problem?

**Comment by neillee95** [comment]
> @neillee95 does the bat script have the same problem?
> 
> 

i think so, but i have not tried

**Comment by neillee95** [comment]
> > @neillee95 does the bat script have the same problem?
> 
> i think so, but i have not tried

i tried, it is

**Review by a364176773 — APPROVED** [review]
LGTM  Please register the pr to develop.md https://github.com/seata/seata/tree/develop/changes

**Comment by a364176773** [comment]
You seem to have other pr's mixed in with your code, please take them out

**Comment by slievrly** [comment]
1.  git pull seata/seata develop
2. git push neillee95/seata develop

**Pull request closed without merging**
