### PR TITLE
bugfix: oracle initialize script index_name is duplicate

### PR DESCRIPTION
**Pull request by PeppaO**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
修复：oracle.sql脚本执行错误，索引名重复

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM  @jsbxyyx PTAL

**Review by jsbxyyx — APPROVED** [review]
LGTM

**Comment by jsbxyyx** [comment]
develop.md补充下作者和pr信息

**Review by l81893521 — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
LGTM, @PeppaO thanks for your contributions.

**Pull request merged**
