### PR TITLE
optimize: remove duplicated word

### PR DESCRIPTION
**Pull request by jammesliu**
- [x] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### CODE REVIEW

**Review by pengten — APPROVED** [review]
LGTM

**Comment by pengten** [comment]
Please add the "optimize: " before the title

**Comment by jammesliu** [comment]
got it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: pengten ***@***.***>
发送时间: Wednesday, March 23, 2022 4:30:07 PM
收件人: seata/seata ***@***.***>
抄送: Z-Entity ***@***.***>; Author ***@***.***>
主题: Re: [seata/seata] remove duplicated word (PR #4482)


Please add the "optimize: " before the title

―

**Comment by slievrly** [comment]
@jammesliu  hope you can find more similar issues and submit them together.

**Pull request merged**
