### PR TITLE
bugfix: fix saga autoType convert error

### PR DESCRIPTION
**Pull request by wt-better**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
FIX [5633](https://github.com/seata/seata/issues/5633)

### CODE REVIEW

**Comment by slievrly** [comment]
@wt-better sign the CLA.

**Review by slievrly — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
@wt-better cherry-pick on branch 2.x and add change in 2.0.0.md.

**Comment by wt-better** [comment]
ok

**Pull request merged**
