### PR TITLE
test: add AT transaction mode tests to support database data types (Oracle)

### LINKED ISSUE #4364: [task] Add AT transaction mode tests to support database data types (Oracle)
## Why you need it?
 Is your feature request related to a problem? Please describe in details

Add AT transaction mode tests to support database data types (Oracle)
增加 AT事务模式中对数据库数据类型的测试，当前任务针对Oracle

The purpose of the test case is to verify that the COMMIT and ROLLBACK are correct 
测试case目的是验证commit和rollback的正确性

Code can be submitted on the https://github.com/seata/seata-test or https://github.com/seata/seata/tree/develop/test
提交的代码可以放到 https://github.com/seata/seata-test 或  https://github.com/seata/seata/tree/develop/test

In this issue, tasks will be disassembled according to the classification of data types.
这个issue中会按照数据类型做分类拆解，按找数据类型的分类进行任务的拆解。

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by doubleDimple**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
test AT mode dataType for oracle

### Ⅱ. Does this pull request fix one issue?

fixes #4364

### CODE REVIEW

**Comment by slievrly** [comment]
@doubleDimple add oracle dependence may cause license problems.

**Comment by doubleDimple** [comment]
AT模式下ORACLE数据库测试结果

系统:mac OS
数据库版本 oracle 11g

测试数据类型：
1 String_type :CHAR NCHAR VARCHAR VARCHAR2 NVARCHAR2 
2 number_type  NUMBER INTEGER DECIMAL NUMERIC DEC
3 date_type date timestamp timestamp(3) with time zone timestamp(3) with local time zone
4 binary_type BLOB CLOB NCLOB BFILE

测试问题
一: 不支持timestamp timestamp(3) with time zone timestamp(3) with local time zone
     1:timestamp会当date处理,导致decoder报错
     2:timestamp(3) with time zone和timestamp(3) with local time zone会返回对象，需要转为offSetDateTime进行处理

二：不支持NCCLOB和BFILE
     1:不兼容NCCLOB，
     2:不支持BFILE,生成beforeImage报错，encoder问题，

**Comment by doubleDimple** [comment]
@slievrly when test finished I remove oracle dependency

**Comment by slievrly** [comment]
> AT模式下ORACLE数据库测试结果
> 
> 系统:mac OS 数据库版本 oracle 11g
> 
> 测试数据类型： 1 String_type :CHAR NCHAR VARCHAR VARCHAR2 NVARCHAR2 2 number_type NUMBER INTEGER DECIMAL NUMERIC DEC 3 date_type date timestamp timestamp(3) with time zone timestamp(3) with local time zone 4 binary_type BLOB CLOB NCLOB BFILE
> 
> 测试问题 一: 不支持timestamp timestamp(3) with time zone timestamp(3) with local time zone 1:timestamp会当date处理,导致decoder报错 2:timestamp(3) with time zone和timestamp(3) with local time zone会返回对象，需要转为offSetDateTime进行处理
> 
> 二：不支持NCCLOB和BFILE 1:不兼容NCCLOB， 2:不支持BFILE,生成beforeImage报错，encoder问题，

@doubleDimple thanks for your contribution.

**Review by doubleDimple — COMMENTED** [review]
learn how to review

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by a364176773** [comment]
https://github.com/seata/seata/pull/4542/files

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
