### PR TITLE
bugfix: remove `@EnableConfigurationProperties({SagaAsyncThreadPoolProperties.class})`

### PR DESCRIPTION
**Pull request by crazy-sheep**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

删除SagaAsyncThreadPoolExecutorConfiguration类上的@EnableConfigurationProperties({SagaAsyncThreadPoolProperties.class})注解。
### Ⅱ. Does this pull request fix one issue?

fixes #https://github.com/seata/seata/issues/5020

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Comment by wangliang181230** [comment]
多余的import移除一下。
```log
Error:  io/seata/spring/boot/autoconfigure/SeataSagaAutoConfiguration.java:39:8: Unused import - org.springframework.boot.context.properties.EnableConfigurationProperties. [UnusedImports]
```

**Comment by a364176773** [comment]
https://github.com/seata/seata/tree/develop/changes 将作者信息和pr信息登记至其中2个文件夹的develop.md中

**Review by slievrly — COMMENTED** [review]
LGTM

**Pull request merged**
