### PR TITLE
use checkstyle in maven to check code

### LINKED ISSUE #797: Use CheckStyle to style the code
## Why you need it?

Everyone contributed to the code will have some different code style, as I mentioned , there are 

image

some check warnings.

so when  I  change the code, there will be some other extra changes. like whitespace (maybe we can use idea etc, but it depends on the settings of users).

and the style file needs some changes, like Alibaba match, and remove author, etc, for open source community

## How it could be?

config 

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <configuration>
                            <configLocation>./style/feats_checkstyle.xml</configLocation>
                            <encoding>UTF-8</encoding>
                            <consoleOutput>true</consoleOutput>
                            <failsOnError>false</failsOnError>
                            <failOnViolation>false</failOnViolation>
                        </configuration>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
because of the history of the project, the settings  should be  false, after we changed all the false style, we can set it as true.
``` 
<failsOnError>false</failsOnError>
<failOnViolation>false</failOnViolation>
```

### PR DESCRIPTION
**Pull request by leizhiyuan**
### Ⅰ. Describe what this PR did
1. use checkstyle in maven to check code
2. fix copyright check error
3. remove @ author check

### Ⅱ. Does this pull request fix one issue?

fixes #797 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

do not need

### Ⅳ. Describe how to verify it

`mvn clean install -DskipTests=true` you will see the result. some code needs to be cleaned next pr

### CODE REVIEW

**Comment by zhangthen** [comment]
Well done, we will merge it between 0.5.0 and 0.6.0.

**Comment by leizhiyuan** [comment]
license need to be formatted in other commit

**Comment by zhangthen** [comment]
Which codestyle do you use ?

**Comment by leizhiyuan** [comment]
> Which codestyle do you use ?

https://github.com/alibaba/p3c/blob/master/p3c-formatter/eclipse-codestyle.xml this style

p3c seems has no other codestyle for maven checkstyle plugin

**Comment by leizhiyuan** [comment]
p3c has not support for checkstyle https://github.com/alibaba/p3c/issues/265

in SOFARPC, we use 
```
  <plugin>
                <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
                <artifactId>maven-java-formatter-plugin</artifactId>
                <version>0.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <configFile>${user.dir}/tools/codestyle/formatter.xml</configFile>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
```

this will format when maven clean install, do you have any idea?

**Pull request merged**
