### PR TITLE
doc: update console-fe readme

### LINKED ISSUE #5440: Docs: console-fe README mirror address update
## Why you need it?
 Is your feature request related to a problem? Please describe in details

registry.npm.taobao.org 需要更新成 https://registry.npmmirror.com

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by jsbxyyx**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅱ. Does this pull request fix one issue?

fixes #5440

### CODE REVIEW

**Comment by slievrly** [comment]
#4923 license compatibility  failed.

**Comment by jsbxyyx** [comment]
- universal-element [https://www.npmjs.com/package/universal-element](https://www.npmjs.com/package/universal-element) BSD-3-Clause
- universal-canvas-context [https://www.npmjs.com/package/universal-canvas-context](https://www.npmjs.com/package/universal-canvas-context) BSD-3-Clause
- @gcanvas/core [https://www.npmjs.com/package/@gcanvas/core](https://www.npmjs.com/package/@gcanvas/core) none
- universal-env [https://www.npmjs.com/package/universal-env](https://www.npmjs.com/package/universal-env) none

**Comment by slievrly** [comment]
> * universal-element https://www.npmjs.com/package/universal-element BSD-3-Clause
> * universal-canvas-context https://www.npmjs.com/package/universal-canvas-context BSD-3-Clause
> * @gcanvas/core https://www.npmjs.com/package/@gcanvas/core none
> * universal-env https://www.npmjs.com/package/universal-env none

Consider temporarily adding these dependencies to the exclusion list of license check, and deal with it after merged this pr.

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
