### PR TITLE
docs: optimize the contribution guide to avoid the obscurity of literal translation

### PR DESCRIPTION
**Pull request by leon2LF**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

优化语句更易懂

### CODE REVIEW

**Comment by leon2LF** [comment]
@a364176773  can you  review my change ？

**Review by slievrly — APPROVED** [review]
LGTM,  add change in 2.x.md

**Review by l81893521 — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by a364176773** [comment]
add change in 2.x.md

**Pull request merged**
