### PR TITLE
[release] release 1.0.0

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

[vote] vote for 1.0.0 release

### CODE REVIEW

**Comment by slievrly** [comment]
@all please vote whether to release 1.0.0 based on the regression test results of 1.0.0-snapshot.

**Comment by xingfudeshi** [comment]
I vote for release GA.
Tested using develop branch code and springboot-mybatis sample.

**Comment by long187** [comment]
I vote for release GA.

**Comment by jsbxyyx** [comment]
I vote for release GA.

**Comment by zhangthen** [comment]
I vote for release GA.

**Comment by lovepoem** [comment]
I support to  release the GA

**Comment by zjinlei** [comment]
I vote for release GA.

**Pull request merged**
