### PR TITLE
feature: make seata-bom be the real Bill-Of-Material

### LINKED ISSUE #3761: Inccorect BOM definition
BOM, aka Bill-of-Material, is a "pom" type artifact that **declare all modules with version of current component**.
Commonly, BOMs should NOT contain declarations not belong to current component.
However, `seata-bom` imports `spring-framework-bom` and declares all dependencies seata use except the seata modules.
This is really a bad practice and it breaks the semantic of BOM!

### PR DESCRIPTION
**Pull request by JasonMing**
### Ⅰ. Describe what this PR did

Add all deployable modules with "jar" packaging to seata-bom's `dependencyManagement`.
All the users could import `seata-bom` to align the version of their seata dependencies.

### Ⅱ. Does this pull request fix one issue?

fixes #3761

### CODE REVIEW

**Comment by JasonMing** [comment]
There is two force-push for correct the gpg sign issue, don't mind it.

**Comment by wangliang181230** [comment]
The `maven-javadoc-plugin` is not required for the seata-bom.

**Comment by JasonMing** [comment]
> The `maven-javadoc-plugin` is not required for the seata-bom.

`maven-gpg-plugin` is also not required because seata-bom does not produce a jar, I'll remove them together.

**Comment by wangliang181230** [comment]
optimize `seata-all`:
```
<includes>
    <include>io.seata:*:*</include>
</includes>
```

**Review by slievrly — APPROVED** [review]
LGTM

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Pull request merged**
