### PR TITLE
optimize: do not execute triggerAfterCommit() in case of timeout

### PR DESCRIPTION
**Pull request by miaoxueyu**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
direct use of TransactionManager.commit () whether do check is timeout

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM 标题要改下，pr做个登记

**Comment by miaoxueyu** [comment]
> 

马上改好，话说 https://github.com/seata/seata/pull/4445/files 这个PR也忘记登记了怎么办，要不要重新在这个PR里补一下

**Comment by slievrly** [comment]
> > 
> 
> 马上改好，话说 https://github.com/seata/seata/pull/4445/files 这个PR也忘记登记了怎么办，要不要重新在这个PR里补一下

go ahead.

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
Does a TimeoutRollback transaction execute the before commit hook cause business inconsistency issues?

**Pull request merged**
