### PR TITLE
optimize: exclude log4j dependencies

### LINKED ISSUE #4404: docker镜像里有log4j-1.2.17.jar
```bash
~ docker run -ti --rm --entrypoint sh seataio/seata-server:1.4.2
/seata-server # ls -l /seata-server/libs/ | grep log4j
-rw-r--r--    1 root     root        489884 Jan  1  1970 log4j-1.2.17.jar

~ docker run -ti --rm --entrypoint sh seataio/seata-server:latest
# ls -l /seata-server/libs/ | grep log4j
-rw-r--r-- 1 root root  489884 Jan  1  1970 log4j-1.2.17.jar
-rw-r--r-- 1 root root  292301 Jan  1  1970 log4j-api-2.13.3.jar
-rw-r--r-- 1 root root   17461 Jan  1  1970 log4j-to-slf4j-2.13.3.jar
```

https://logging.apache.org/log4j/1.2/index.html

log4j 1.2 已经不再维护且有很多漏洞

### PR DESCRIPTION
**Pull request by pengten**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
移除对log4j的依赖
exclude log4j dependencies

### Ⅱ. Does this pull request fix one issue?

fixes #4404

### CODE REVIEW

**Review by a364176773 — COMMENTED** [review]
seata-discovery-zk是否也需要排除?

**Comment by pengten** [comment]
> seata-discovery-zk

没发现这个模块有log4j依赖呢

**Comment by pengten** [comment]
> seata-discovery-zk是否也需要排除?

之前从seata-server没检索到discovery的依赖；保险一点，都给排除了。

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by slievrly — COMMENTED** [review]
LGTM

**Pull request merged**
