### PR TITLE
Added tests for com.alibaba.fescar.core.protocol.AbstractMessage

### PR DESCRIPTION
**Pull request by freddytuxworth**
I have analysed this codebase and found a few gaps in coverage of AbstractMessage.java.
I have written a few tests for this class with the help of [Diffblue](http://diffblue.com/) [Cover](https://www.diffblue.com/datasheet), which hopefully should help you to spot any regressions caused by future code changes.

Also, I noticed a possibly unwanted behaviour of `bytesToInt`: if an array is provided which is shorter than the 4 bytes needed for an int, the available bytes take the lowest positions in the returned int.
For example, `bytesToInt(new byte[] {0, 1}, 0)` will return 1, rather than 65536. This functionality is tested in `bytesToIntOffsetZeroTruncated`, but you may want to adapt this test and fix the functionality if this is a bug.

### CODE REVIEW

**Comment by slievrly** [comment]
@freddytuxworth please ping me

**Comment by diffblue-assistant** [comment]
> @freddytuxworth please ping me

ping you? by email?

**Comment by freddytuxworth** [comment]
@slievrly ^

**Comment by slievrly** [comment]
@freddytuxworth dingTalk @slievrly

**Comment by freddytuxworth** [comment]
@slievrly I emailed you to confirm that we have signed the CLA, is there any other problem?

**Pull request closed without merging**
