### PR TITLE
test: fix zookeeper UT failed

### LINKED ISSUE #5923: zk unit test error
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by slievrly**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

try fix zookeeper UT failed

### Ⅱ. Does this pull request fix one issue?

fixes #5923

fixes #5952

### CODE REVIEW

**Comment by slievrly** [comment]
first round: https://github.com/seata/seata/actions/runs/6639838130/job/18039020531?pr=5960

I will retry the CICD workflow.

**Comment by slievrly** [comment]
second round: https://github.com/seata/seata/actions/runs/6639838130/job/18039331533?pr=5960

**Comment by slievrly** [comment]
third round: https://github.com/seata/seata/actions/runs/6639838130/job/18039805703?pr=5960

**Comment by slievrly** [comment]
all the check pass.
image

**Review by funky-eyes — APPROVED** [review]
LGTM

**Pull request merged**
