### PR TITLE
optimize: support jmx port in seata

### LINKED ISSUE #5269: support jmx port for seata-server.sh
## Why you need it?
 Is your feature request related to a problem? Please describe in details
方便jvm相关的exporter或jconsole采集线程数，gc次数等metric数据，应该开放jmx port的设置

```
JMX_PORT=$JMX_PORT
JMX_OPTS=$JMX_OPTS
if [ -z "$JMX_OPTS" ]; then
  JMX_OPTS=" -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false "
fi

if [ -z "$JMX_PORT" ]; then
  JMX_OPTS=" $JMX_OPTS -Dcom.sun.management.jmxremote.port=${JMX_PORT:="10055"} -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT:="10055"} "
fi
```

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by leizhiyuan**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?
fixes #5269

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

image

### Ⅳ. Describe how to verify it

1. `export JMX_ENABLE=true`
2.  run in local machine, check the opts

### CODE REVIEW

**Comment by leizhiyuan** [comment]
> I don't think any feature that isn't part of a transaction should be claimed as a feature

ok, thanks for your advice, I have changed commit message and title

**Review by funky-eyes — APPROVED** [review]
LGTM Please register pr and author information to https://github.com/seata/seata/blob/2.x/changes/zh-cn/2.0.0.md https://github.com/seata/seata/blob/2.x/changes/en-us/2.0.0.md 
and synchronize the changes to the develop branch.

**Comment by leizhiyuan** [comment]
> LGTM Please register pr and author information to https://github.com/seata/seata/blob/2.x/changes/zh-cn/2.0.0.md https://github.com/seata/seata/blob/2.x/changes/en-us/2.0.0.md and synchronize the changes to the develop branch.

ok

**Review by funky-eyes — COMMENTED** [review]
You also need to register the githubid in 2.0.0.md

**Comment by leizhiyuan** [comment]
> You also need to register the githubid in 2.0.0.md

done

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
