### PR TITLE
release: release for 1.8.0

### PR DESCRIPTION
**Pull request by slievrly**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

vote for release 1.8.0 (https://github.com/seata/seata/milestone/30)

at least 3 votes with binding to pass

result:
+4 binding
- @funky-eyes 
- @leizhiyuan 
- @xingfudeshi 
- @slievrly 

Please vote accordingly:
- [x] +1 approve
- [x] +0 no opinion
- [x] -1 disapprove with the reason

vote result:

### CODE REVIEW

**Review by funky-eyes — APPROVED** [review]
LGTM  +1 approve
image

**Comment by leizhiyuan** [comment]
+1 approve

**Review by leizhiyuan — APPROVED** [review]

**Comment by slievrly** [comment]
@leizhiyuan Are there any tests?

**Comment by leizhiyuan** [comment]
> @leizhiyuan Are there any tests?

run in develop branch,  seata run in mode of db

**Review by xingfudeshi — APPROVED** [review]
+1 approve
AT file mode
seata-spring-boot-starter
docker

**Comment by slievrly** [comment]
The SDK compatibility test failed,  I have submit an issue #5978, and fix it later.
https://github.com/seata/seata/actions/runs/6664592306/job/18183499470

Functional test：
seata-server image: seataio/seata-server:1.8.0-SNAPSHOT,  registry: Nacos, SDK: 1.8.0-SNAPSHOT(from https://oss.sonatype.org/#welcome)

- AT MySQL 5.7, DML commit and rollback, Using Dubbo and Spring Cloud Alibaba.  test is ok.
- AT Oracle 19c,  DML commit and rollback(lower and upper case), Using Dubbo and Spring Cloud Alibaba.  test is ok.

**Comment by slievrly** [comment]
+1 binding
CI-check

**Comment by slievrly** [comment]
vote result:
+4 binding
- @funky-eyes 
- @leizhiyuan 
- @xingfudeshi 
- @slievrly 

I will merge this PR and release 1.8.0 soon.

**Pull request merged**
