### PR TITLE
optimize: optimize `collectRowLocks` method.

### PR DESCRIPTION
**Pull request by tian-qingzhao**

### CODE REVIEW

**Comment by a364176773** [comment]
可以把源码中所有类似的地方都找到一并修改吗？

**Comment by tian-qingzhao** [comment]
> 可以把源码中所有类似的地方都找到一并修改吗？

Sorry, this is all I can see so far.  I will continue to submit if I see any more.

**Comment by a364176773** [comment]
> > 可以把源码中所有类似的地方都找到一并修改吗？
> 
> Sorry, this is all I can see so far. I will continue to submit if I see any more.

ok, we'll wait for you to add it to this pr

**Comment by tian-qingzhao** [comment]
> > > 可以把源码中所有类似的地方都找到一并修改吗？
> > 
> > 
> > Sorry, this is all I can see so far. I will continue to submit if I see any more.
> 
> ok, we'll wait for you to add it to this pr



> > > 可以把源码中所有类似的地方都找到一并修改吗？
> > 
> > 
> > Sorry, this is all I can see so far. I will continue to submit if I see any more.
> 
> ok, we'll wait for you to add it to this pr

I think we should merge the branches first and make sure that each branch only does one thing.  No similar code has been found anywhere else.

**Comment by a364176773** [comment]
> > > > 可以把源码中所有类似的地方都找到一并修改吗？
> > > 
> > > 
> > > Sorry, this is all I can see so far. I will continue to submit if I see any more.
> > 
> > 
> > ok, we'll wait for you to add it to this pr
> 
> > > > 可以把源码中所有类似的地方都找到一并修改吗？
> > > 
> > > 
> > > Sorry, this is all I can see so far. I will continue to submit if I see any more.
> > 
> > 
> > ok, we'll wait for you to add it to this pr
> 
> I think we should merge the branches first and make sure that each branch only does one thing. No similar code has been found anywhere else.

I think it's the same thing

**Pull request merged**
