### PR TITLE
release: release for release 1.4.2

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

### Ⅰ. Describe what this PR did

vote for release 1.4.2
at least 3 votes with binding to pass

Please vote accordingly:
- [x] +1 approve
- [x] +0 no opinion
- [x] -1 disapprove with the reason

### CODE REVIEW

**Comment by long187** [comment]
+1 approve

**Comment by a364176773** [comment]
+1 approve
at+db and at+redis

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by l81893521 — APPROVED** [review]
LGTM

**Comment by slievrly** [comment]
seata-all + AT + Dubbo  + @EnableAutoDataSourceProxy +MYSQL +  commit/rollback
seata-spring-boot-starter + AT + Spring Cloud  feign/restTemplate  +MYSQL +  commit/rollback

**Pull request merged**
