### PR TITLE
bugfix: fix the issue of saved branch session status does not match the actual branch session status

### LINKED ISSUE #5953: saved branch session status does not match the actual branch session status
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

lifecycleListener.onAddBranch() saves the branch session with unknow status, branchSession.setStatus(BranchStatus.Registered) sets branch session status to Registered, the saved branch session status does not match the actual branch session status.

### Ⅰ. Issue Description
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by Aruato**
…he actual branch session status(https://github.com/seata/seata/issues/5953)

- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #5953

### CODE REVIEW

**Comment by leizhiyuan** [comment]
Personal opinion, if we simply change  `branchSession.setStatus(BranchStatus.Registered);`  to `changeBranchStatus(branchSession, BranchStatus.Registered);`  not only can we fix the issue, but we can also track the changes in status. It seems more reasonable, but the downside is that we need to writeSession twice.

**Review by funky-eyes — CHANGES_REQUESTED** [review]
globalsession is in the future refactoring plan, it will be clearly differentiated from the sessionmanager's responsibilities, and this change is better suited to changes in SessionHelper#newBranchByGlobal

**Comment by Aruato** [comment]
> Personal opinion, if we simply change  `branchSession.setStatus(BranchStatus.Registered);`  to `changeBranchStatus(branchSession, BranchStatus.Registered);`  not only can we fix the issue, but we can also track the changes in status. It seems more reasonable, but the downside is that we need to writeSession twice.

Personal opinion, lifecycleListener.onAddBranch() means add branch session, as long as the branch session can be added successfully, then the initial state of the branch session should be Registered, because at this time the branch session has been associated with the global session through the xid, since it has been associated, then the initial state should not be Unknown.

So I think it makes more sense to set the state to Registered before lifecycleListener.onAddBranch().

**Comment by Aruato** [comment]
Personal opinion, lifecycleListener.onAddBranch() means add branch session, as long as the branch session can be added successfully, then the initial state of the branch session should be Registered, because at this time the branch session has been associated with the global session through the xid, since it has been associated, then the initial state should not be Unknown.

So I think it makes more sense to set the state to Registered before lifecycleListener.onAddBranch().





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lei ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 上午8:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [seata/seata] bugfix: fix the issue of saved branch session status does not match the actual branch session status (PR #5954)





 
Personal opinion, if we simply change  branchSession.setStatus(BranchStatus.Registered);  to changeBranchStatus(branchSession, BranchStatus.Registered);  not only can we fix the issue, but we can also track the changes in status. It seems more reasonable, but the downside is that we need to writeSession twice.

**Comment by leizhiyuan** [comment]
> globalsession is in the future refactoring plan, it will be clearly differentiated from the sessionmanager's responsibilities, and this change is better suited to changes in SessionHelper#newBranchByGlobal

make sense, the init state should be Registered(which means ininted here) when construct a new branch from global session

**Comment by funky-eyes** [comment]
> > globalsession is in the future refactoring plan, it will be clearly differentiated from the sessionmanager's responsibilities, and this change is better suited to changes in SessionHelper#newBranchByGlobal
> 
> make sense, the init state should be Registered(which means ininted here) when construct a new branch from global session

ok, I get it.

**Review by funky-eyes — COMMENTED** [review]
I think the reason why I didn't change the state to memory when I added the branchsession is because of these points: 
1. there is an overhead of inserting and updating twice, which has a big impact on the db and redis schema 
2. the state of the branchsession is of no use to tc, except for the state of a failed stage.

我认为当时为什么在加入该branchsession时，没有将状态更改到存储器中的原因应该是这几点：
1. 存在insert与update 两次开销，对于db和redis模式影响较大
2. branchsession的状态除了一阶段失败这个状态外，对于tc而言没有其他用处

**Comment by Aruato** [comment]
> I think the reason why I didn't change the state to memory when I added the branchsession is because of these points:
> 
> 1. there is an overhead of inserting and updating twice, which has a big impact on the db and redis schema
> 2. the state of the branchsession is of no use to tc, except for the state of a failed stage.
> 
> 我认为当时为什么在加入该branchsession时，没有将状态更改到存储器中的原因应该是这几点：
> 
> 1. 存在insert与update 两次开销，对于db和redis模式影响较大
> 2. branchsession的状态除了一阶段失败这个状态外，对于tc而言没有其他用处

Yes, only PhaseOne_Failed status is used by TC。personal opinion, there are two solutions:
1. set the initial state to Registered when creating the branch session.
2. set Registered status like global session how to set begin status：initial status is still Unknown but set status as begin before lifecycleListener.onBegin(this) writes to db/redis/file (which is what my PR did)

是的，只有PhaseOne_Failed状态被TC使用到。个人观点，解决办法有两种：
1. 在创建branch session时就直接将初始状态设置为Registered
2. 像global session设置begin状态那样去处理：初始状态仍然为Unknown状态，但是在lifecycleListener.onBegin(this)将global session写入到db/redis/file之前将状态设置为begin（这也是我提交的PR所做的）

**Comment by funky-eyes** [comment]
> > I think the reason why I didn't change the state to memory when I added the branchsession is because of these points:
> > 
> > 1. there is an overhead of inserting and updating twice, which has a big impact on the db and redis schema
> > 2. the state of the branchsession is of no use to tc, except for the state of a failed stage.
> > 
> > 我认为当时为什么在加入该branchsession时，没有将状态更改到存储器中的原因应该是这几点：
> > 
> > 1. 存在insert与update 两次开销，对于db和redis模式影响较大
> > 2. branchsession的状态除了一阶段失败这个状态外，对于tc而言没有其他用处
> 
> Yes, only PhaseOne_Failed status is used by TC。personal opinion, there are two solutions:
> 
> 1. set the initial state to Registered when creating the branch session.
> 2. set Registered status like global session how to set begin status：initial status is still Unknown but set status as begin before lifecycleListener.onBegin(this) writes to db/redis/file (which is what my PR did)
> 
> 是的，只有PhaseOne_Failed状态被TC使用到。个人观点，解决办法有两种：
> 
> 1. 在创建branch session时就直接将初始状态设置为Registered
> 2. 像global session设置begin状态那样去处理：初始状态仍然为Unknown状态，但是在lifecycleListener.onBegin(this)将global session写入到db/redis/file之前将状态设置为begin（这也是我提交的PR所做的）

I'm more in favor of option 1, and I wonder what others think?
我更赞成方案1,不知道大家怎么看? @slievrly

**Comment by leizhiyuan** [comment]
> > > I think the reason why I didn't change the state to memory when I added the branchsession is because of these points:
> > > 
> > > 1. there is an overhead of inserting and updating twice, which has a big impact on the db and redis schema
> > > 2. the state of the branchsession is of no use to tc, except for the state of a failed stage.
> > > 
> > > 我认为当时为什么在加入该branchsession时，没有将状态更改到存储器中的原因应该是这几点：
> > > 
> > > 1. 存在insert与update 两次开销，对于db和redis模式影响较大
> > > 2. branchsession的状态除了一阶段失败这个状态外，对于tc而言没有其他用处
> > 
> > 
> > Yes, only PhaseOne_Failed status is used by TC。personal opinion, there are two solutions:
> > 
> > 1. set the initial state to Registered when creating the branch session.
> > 2. set Registered status like global session how to set begin status：initial status is still Unknown but set status as begin before lifecycleListener.onBegin(this) writes to db/redis/file (which is what my PR did)
> > 
> > 是的，只有PhaseOne_Failed状态被TC使用到。个人观点，解决办法有两种：
> > 
> > 1. 在创建branch session时就直接将初始状态设置为Registered
> > 2. 像global session设置begin状态那样去处理：初始状态仍然为Unknown状态，但是在lifecycleListener.onBegin(this)将global session写入到db/redis/file之前将状态设置为begin（这也是我提交的PR所做的）
> 
> I'm more in favor of option 1, and I wonder what others think? 我更赞成方案1,不知道大家怎么看? @slievrly

agree with option 1

**Review by funky-eyes — APPROVED** [review]
LGTM 
Please register author and pr information to: https://github.com/seata/seata/blob/2.x/changes/zh-cn/2.0.0.md
& https://github.com/seata/seata/blob/2.x/changes/en-us/2.0.0.md

**Comment by funky-eyes** [comment]
We should have agreed on this, please make the initial state changes in `newBranchByGlobal`.

**Comment by Aruato** [comment]
> We should have agreed on this, please make the initial state changes in `newBranchByGlobal`.

Okay, I've changed it.

**Pull request merged**
