### PR TITLE
optimize: file session manager changed to singleton and optimize task thread pool model

### PR DESCRIPTION
**Pull request by a364176773**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did
等待https://github.com/seata/seata/pull/4393 合并后进行合并
将file下多例改为单例 
定时任务回滚回原先的4个任务，仅做status筛选查询

### CODE REVIEW

**Comment by slievrly** [comment]
[DefaultCoordinator.java](https://github.com/seata/seata/pull/4451/files#diff-872c82537b69a4b0b403576da75a7609394892538e65feb4ffee95748d5f1a1c)  exclude `GlobalStatus.AsyncCommitting`

**Comment by slievrly** [comment]
Whether to need to increase the ASYNC_COMMITTING processing threads,  In general, globalCommit transactions are the majority and there is a potential OOM risk in file mode.

**Comment by a364176773** [comment]
> Whether to need to increase the ASYNC_COMMITTING processing threads, In general, globalCommit transactions are the majority and there is a potential OOM risk in file mode.

需要重试提交的情况出现几率比较低，单独使用一个线程去查询的开销我认为是不值得的，且在file模式下是没有查询条数限制，对于异步提交来说不会有太大的影响
the probability of retrying a commit is low, the cost of using a single thread to query is not worth it, and there is no limit to the number of queries in file mode, there is no significant impact on an asynchronous commit

**Comment by a364176773** [comment]
@caohdgege @slievrly @wangliang181230 @l81893521 PTAL

**Review by slievrly — APPROVED** [review]
LGTM

**Review by caohdgege — APPROVED** [review]
LGTM

**Pull request merged**
