### PR TITLE
fix doc

### PR DESCRIPTION
**Pull request by IanCao**

### CODE REVIEW

**Comment by IanCao** [comment]
> please related your github ID

I cant get your point -_-

**Comment by slievrly** [comment]
image
@IanCao

**Comment by xingfudeshi** [comment]
git config --global user.name "username"
git config --global user.email "email"
use the above commands to config your username and email，then these two informations will be attached with every commit of you,so we can valid the source of commit.remember that the username and email should be exactly same as what they are in your github account.

**Comment by IanCao** [comment]
> git config --global user.name "username"
> git config --global user.email "email"
> use the above commands to config your username and email，then these two informations will be attached with every commit of you,so we can valid the source of commit.remember that the username and email should be exactly same as what they are in your github account.

ok,i know.
i'll changed caoyixiong to IanCao and open a new pr.

**Pull request closed without merging**
