### PR TITLE
fix bug of file based manager

### LINKED ISSUE #808: a possible bug of FileBasedSessionManager
- [x] I have searched the [issues](https://github.com/alibaba/fescar/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

the full file name is not right.

### Ⅱ. Describe what happened
```
   /**
     * Instantiates a new File based session manager.
     *
     * @param name                 the name
     * @param sessionStoreFilePath the session store file path
     * @throws IOException the io exception
     */
    public FileBasedSessionManager(String name, String sessionStoreFilePath) throws IOException {
        super(name);
        transactionStoreManager = new FileTransactionStoreManager(sessionStoreFilePath + name, this);
    }
```
the full name is not right 

### Ⅲ. Describe what you expected to happen

```
store {
  ## store mode: file、db
  mode = "file"

  ## file store
  file {
    dir = "root.data"
```
this should be dir, not the file name.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by leizhiyuan**
### Ⅰ. Describe what this PR did

only add this line, others are format style.

image

### Ⅱ. Does this pull request fix one issue?

fixes #808 , the depends on which user should config

xxx/xxx
or
xxx/xxx/

when add  File.separator, we will support these two ways.

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

the original test case failed when you run. maybe it did not run in ci.

### Ⅳ. Describe how to verify it

test case will success

### CODE REVIEW

**Comment by leizhiyuan** [comment]
'store.file.dir' , now I set it as sessionStore, if you have any idea, please comment

**Comment by slievrly** [comment]
> 'store.file.dir' , now I set it as sessionStore, if you have any idea, please comment

if dir contains File.separator? ref File(String parent, String child)  compatible with two forms

**Comment by leizhiyuan** [comment]
> > 'store.file.dir' , now I set it as sessionStore, if you have any idea, please comment
> 
> if dir contains File.separator? ref File(String parent, String child) compatible with two forms

after the pr

```
   public FileBasedSessionManager(String name, String sessionStoreFilePath) throws IOException {
        super(name);
        transactionStoreManager = new FileTransactionStoreManager(sessionStoreFilePath + File.separator + name, this);
    }
```

It will be ok whether dir has File.separator or not.

**Comment by zhangthen** [comment]
@leizhiyuan   Recommit after 0.5.0

**Comment by slievrly** [comment]
@leizhiyuan modify pr title.

**Pull request merged**
