### PR TITLE
refactor: add sql parser type druid as constant

### PR DESCRIPTION
**Pull request by ggndnn**
### Ⅰ. Describe what this PR did

According to the last review comment in #1703, added sql parser type druid as constant.

### CODE REVIEW

**Comment by zjinlei** [comment]
Could it be an enumeration class that put more sql parsers type?

**Comment by ggndnn** [comment]
> Could it be an enumeration class that put more sql parser types?

How about an abstract class contains sql parser type constants? Because `@LoadLevel(name = "druid")` needs constants. Any suggestion?

**Comment by zjinlei** [comment]
> > Could it be an enumeration class that put more sql parser types?
> 
> How about an abstract class contains sql parser type constants? Because `@LoadLevel(name = "druid")` needs constants. Any suggestion?

Enumeration attributes are constants, so why not consider it?
I think it is possible to build a SqlParserType class in seata-sqlparser-core.

**Comment by ggndnn** [comment]
> > > Could it be an enumeration class that put more sql parser types?
> > 
> > 
> > How about an abstract class contains sql parser type constants? Because `@LoadLevel(name = "druid")` needs constants. Any suggestion?
> 
> Enumeration attributes are constants, so why not consider it?
> I think it is possible to build a SqlParserType class in seata-sqlparser-core.

`@LoadLevel(name=` needs `String` type constants. I'm not sure how to add enum to it, so my suggestion is to create an abstract class `SqlParserType` contains string type constants or just use `ConfigurationKeys`.

```
public @interface LoadLevel {
    /**
     * Name string.
     *
     * @return the string
     */
    String name();

    /**
     * Order int.
     *
     * @return the int
     */
    int order() default 0;
}
```

**Comment by ggndnn** [comment]
> LGTM. We may need to move ConfigurationKeys to the common module.

This can be considered.

**Comment by ggndnn** [comment]
> > LGTM. We may need to move ConfigurationKeys to the common module.
> 
> This can be considered.

@slievrly 
Need to do this in this pr or in future pr after more extensive discussion?

**Comment by zjinlei** [comment]
> ConfigurationKeys

Sorry, My low-level mistake.
But it is only an constant, not an configuration key, and there will be more sql parser types, I don't think it should be put in ConfigurationKeys.

**Comment by ggndnn** [comment]
> > ConfigurationKeys
> 
> Sorry, My low-level mistake.
> But it is only a constant, not a configuration key, and there will be more sql parser types, I don't think it should be put in ConfigurationKeys.
> Hope that there is a better way, can list more sql parser later.

@zjinlei 

SqlParserType added.

**Pull request merged**
