### PR TITLE
bugfix: BufferOverflow when BranchSession size too large

### LINKED ISSUE #1551: FileTransactionStoreManager.writeDataFile may cause BufferOverflowException
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

when FileTransactionStoreManager write a big BranchSession(size > 16KB), it will cause BufferOverflowException:
```
    private boolean writeDataFile(byte[] bs) {
        if (bs == null) {
            return false;
        }
        ByteBuffer byteBuffer = null;

        if (bs.length > MAX_WRITE_BUFFER_SIZE) {
            //allocateNew
            // **byteBuffer size should by bs.length+4(because byteBuffer will put bs.length)**
            byteBuffer = ByteBuffer.allocateDirect(bs.length);
        } else {
            byteBuffer = writeBuffer;
            //recycle
            byteBuffer.clear();
        }

        byteBuffer.putInt(bs.length);
        byteBuffer.put(bs);
        return writeDataFileByBuffer(byteBuffer);
    }
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
java.nio.BufferOverflowException: null
	at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
	at java.nio.ByteBuffer.put(ByteBuffer.java:859)
	at io.seata.server.store.file.FileTransactionStoreManager.writeDataFile(FileTransactionStoreManager.java:429)
	at io.seata.server.store.file.FileTransactionStoreManager.writeSession(FileTransactionStoreManager.java:175)
	at io.seata.server.store.file.FileTransactionStoreManagerTest.writeBigBytes(FileTransactionStoreManagerTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	....
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

there is a Test to reproduce it 

```
public class FileTransactionStoreManagerTest {

    FileTransactionStoreManager fileTransactionStoreManager;

    @BeforeEach
    public void beforeAll() throws IOException {
        fileTransactionStoreManager = new FileTransactionStoreManager("~/my/tmp/test/seata", null);
    }

    @Test
    public void writeBigBytes() {
        BranchSession branchSession = new BranchSession();
        branchSession.setApplicationData(createBigStr(1024 * 16 - 36));
        fileTransactionStoreManager.writeSession(TransactionStoreManager.LogOperation.BRANCH_ADD, branchSession);
    }

    public String createBigStr(int size){
        byte[] bytes = new byte[size];
        for (int i = 0; i < size; i++) {
            bytes[i] = 'a';
        }
        return new String(bytes);
    }
}
```

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by finalcola**
### Ⅰ. Describe what this PR did

fix BufferOverflowException when FileTransactionStoreManager write a big BranchSession(size > 16KB).

### Ⅱ. Does this pull request fix one issue?

fixes #1551

https://github.com/seata/seata/issues/1551#issue-486308391

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
```
public class FileTransactionStoreManagerTest {

    FileTransactionStoreManager fileTransactionStoreManager;

    @BeforeEach
    public void beforeAll() throws IOException {
        fileTransactionStoreManager = new FileTransactionStoreManager("~/my/tmp/test/seata", null);
    }

    @Test
    public void writeBigBytes() {
        BranchSession branchSession = new BranchSession();
        branchSession.setApplicationData(createBigStr(1024 * 16 - 36));
        fileTransactionStoreManager.writeSession(TransactionStoreManager.LogOperation.BRANCH_ADD, branchSession);
    }

    public String createBigStr(int size){
        byte[] bytes = new byte[size];
        for (int i = 0; i < size; i++) {
            bytes[i] = 'a';
        }
        return new String(bytes);
    }
}
```

### CODE REVIEW

**Comment by finalcola** [comment]
```
ByteBuffer byteBuffer = null;

        if (bs.length > MAX_WRITE_BUFFER_SIZE) {
            //allocateNew
            byteBuffer = ByteBuffer.allocateDirect(bs.length);
        } else {
            byteBuffer = writeBuffer;
            //recycle
            byteBuffer.clear();
        }
        byteBuffer.putInt(bs.length);
        byteBuffer.put(bs);
        return writeDataFileByBuffer(byteBuffer);
```
it's origin code.
when execute : 
```
byteBuffer.putInt(bs.length);
byteBuffer.put(bs);
```
bytebuffer will write extra 4 byte content (bs.length), but when allocate DirectByteBuffer,  the length of the DirectByteBuffer is bs.length ( should be bs.length +4  )

**Comment by slievrly** [comment]
@finalcola    public static ByteBuffer allocateDirect(int capacity)  accept a int param, if bs.len<int.max but bs.len+4>int.max , it need to judge?

**Comment by finalcola** [comment]
MAX_WRITE_BUFFER_SIZE is 16KB not int.max.
when bs.length>MAX_WRITE_BUFFER_SIZE, there will allocate a new ByteBuffer(size = bs.length).
but we put bs.length(int) and bs content into this ByteBuffer, so it will oversize 4B (bs.length) and cause BufferOverflowException.
@slievrly

**Comment by slievrly** [comment]
@finalcola if (bs.length=int.max-1 ) ，can it run normally?

**Comment by finalcola** [comment]
it can't , because byteBuffer always write extra 4 byte content（Larger than the allocated buffer）.
@slievrly

**Comment by slievrly** [comment]
> it can't , because byteBuffer always write extra 4 byte content（Larger than the allocated buffer）.
> @slievrly

So do we need to add code to judge bs.length over int.max?

**Comment by finalcola** [comment]
no,it's already judged before enter this method.

**Comment by slievrly** [comment]
> no,it's already judged before enter this method.

1. private boolean writeDataFile(byte[] bs) 
2. call writeDataFile method with param byte[] bs.(int.max-3<bs.length<int.max)

**Comment by finalcola** [comment]
so we should judge bs.length<=int.max-4?

**Pull request merged**
