### PR TITLE
bugfix: Repair automatically set timeout to 0 when the timeout period is equal to 60000

### LINKED ISSUE #3814: seata1.4.1 版本 注解设置超时时间为60000，会被重置为0
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
seata1.4.1 版本 注解设置超时时间为60000，会被重置为0

### Ⅱ. Describe what happened
代码路径：io.seata.spring.annotation.GlobalTransactionalInterceptor
方法名：Object handleGlobalTransaction(final MethodInvocation methodInvocation, final GlobalTransactional globalTrxAnno)
```
if (timeout <= 0 || timeout == 60000) {
                        timeout = GlobalTransactionalInterceptor.defaultGlobalTransactionTimeout;
                    }
```

### Ⅲ. Describe what you expected to happen
期望结果：如果超时时间小于0，超时时间设置为0即可

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version : 1.8
- OS : mac os
- Others:

### PR DESCRIPTION
**Pull request by liuenci**
### Ⅰ. Describe what this PR did
修复当全局事务注解设置超时时间为60000时，全局事务拦截器会将超时时间设置为0的bug。

### Ⅱ. Does this pull request fix one issue?

fixes #3814 

### Ⅴ. Special notes for reviews
具体修改的代码：
io.seata.tm.api.TransactionalExecutor#getTransactionInfo

### CODE REVIEW

**Comment by wangliang181230** [comment]
@liuenci 
我在issue里回复了你一些信息，你看一下。

**Comment by wangliang181230** [comment]
单单这么改的话，全局配置直接失效了。

**Comment by slievrly** [comment]
@liuenci agree with https://github.com/seata/seata/issues/3814#issuecomment-864702474

**Comment by slievrly** [comment]
@liuenci  any progress here? If not, I think I can close it. I agree with @wangliang181230  on the implementation plan.

**Pull request closed without merging**
