### PR TITLE
bugfix: fix the problem that the propagation attribute 'Propagation.REQUIRES_NEW' is not valid

### LINKED ISSUE #3079: release 1.3.0，全局事务Propagation.REQUIRES_NEW没有正常运行
io.seata.tm.api.TransactionalTemplate中

```
public Object execute(TransactionalExecutor business) throws Throwable {
        // 1 get transactionInfo
        TransactionInfo txInfo = business.getTransactionInfo();
        if (txInfo == null) {
            throw new ShouldNeverHappenException("transactionInfo does not exist");
        }
        // 1.1 get or create a transaction
        GlobalTransaction tx = GlobalTransactionContext.getCurrentOrCreate();

        // 1.2 Handle the Transaction propatation and the branchType
        Propagation propagation = txInfo.getPropagation();
        SuspendedResourcesHolder suspendedResourcesHolder = null;
        try {
            switch (propagation) {
                case NOT_SUPPORTED:
                    suspendedResourcesHolder = tx.suspend(true);
                    return business.execute();
                case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
                case SUPPORTS:
                    if (!existingTransaction()) {
                        return business.execute();
                    }
                    break;
                case REQUIRED:
                    break;
                case NEVER:
                    if (existingTransaction()) {
                        throw new TransactionException(
                                String.format("Existing transaction found for transaction marked with propagation 'never',xid = %s"
                                        ,RootContext.getXID()));
                    } else {
                        return business.execute();
                    }
                case MANDATORY:
                    if (!existingTransaction()) {
                        throw new TransactionException("No existing transaction found for transaction marked with propagation 'mandatory'");
                    }
                    break;
                default:
                    throw new TransactionException("Not Supported Propagation:" + propagation);
            }


            try {

                // 2. begin transaction
                beginTransaction(txInfo, tx);

                Object rs = null;
                try {

                    // Do Your Business
                    rs = business.execute();

                } catch (Throwable ex) {

                    // 3.the needed business exception to rollback.
                    completeTransactionAfterThrowing(txInfo, tx, ex);
                    throw ex;
                }

                // 4. everything is fine, commit.
                commitTransaction(tx);

                return rs;
            } finally {
                //5. clear
                triggerAfterCompletion();
                cleanUp();
            }
        } finally {
            tx.resume(suspendedResourcesHolder);
        }

    }
```

在判断propation之前获取了当前的全局事务对象：
` GlobalTransaction tx = GlobalTransactionContext.getCurrentOrCreate();`

在判断propation时，挂起了当前全局事务：
```
case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
```

但之后执行业务代码之前并没有重新创建全局事务：
```
                // 2. begin transaction
                beginTransaction(txInfo, tx);

                Object rs = null;
                try {

                    // Do Your Business
                    rs = business.execute();

                } catch (Throwable ex) {

                    // 3.the needed business exception to rollback.
                    completeTransactionAfterThrowing(txInfo, tx, ex);
                    throw ex;
                }

                // 4. everything is fine, commit.
                commitTransaction(tx);
```

直至最后，无论是beginTransaction方法、commitTransaction方法还是triggerAfterCompletion里的回滚方法，都是以参与者的身份执行，并不会与TC进行通信，没办法起到Propagation.REQUIRES_NEW的目的

应该在该代码break之前
```
case REQUIRES_NEW:
                    suspendedResourcesHolder = tx.suspend(true);
                    break;
```
重新创建全局事务：
```
tx = GlobalTransactionContext.getCurrentOrCreate();
```

### PR DESCRIPTION
**Pull request by Maestroqiua**
### Ⅰ. Describe what this PR did
bugfix: fix the problem that the propagation attribute 'Propagation.REQUIRES_NEW' is not valid
1. fix the bug that `Propagation.REQUIRES_NEW is not valid
2. add some comments for class `TransactionalTemplate`

### Ⅱ. Does this pull request fix one issue?

fixes #3079

### CODE REVIEW

**Comment by a364176773** [comment]
i hope this isn't plagiarized

**Comment by Maestroqiua** [comment]
> i hope this isn't plagiarized

？？？

I found the problem and gave the solution.

please check the issue 
https://github.com/seata/seata/issues/3079#issue-691774669

and comments 
https://github.com/seata/seata/issues/3079#issuecomment-696567923
https://github.com/seata/seata/issues/3079#issuecomment-697075654
https://github.com/seata/seata/issues/3079#issuecomment-697076341

you have the right to abandon my code
but please don't say anything like plagiarize

**Comment by wangliang181230** [comment]
> 
> 
> i hope this isn't plagiarized

He is the discoverer and solver of the issue.
I think that his PR has not been submitted for too long time, so I submit my local branch first.
I'm sorry for the misunderstanding..

**Comment by Maestroqiua** [comment]
> > i hope this isn't plagiarized
> 
> He is the discoverer and solver of the issue.
> I think that his PR has not been submitted for too long time, so I submit my local branch first.
> I'm sorry for the misunderstanding..

Don't be sorry for this. It's not a big deal.

I just review your pr and code, thought that your pr was not merged, if I commit my code and pr and finally merged, it will be conflicted, so I try to copy the content in your pr. Actually I do the plagiarize thing in some way.

Thanks for your explanation, I will keep reviewing the code and subscribing the seata project when I get any time.

**Comment by a364176773** [comment]
> > > i hope this isn't plagiarized
> > 
> > 
> > He is the discoverer and solver of the issue.
> > I think that his PR has not been submitted for too long time, so I submit my local branch first.
> > I'm sorry for the misunderstanding..
> 
> Don't be sorry for this. It's not a big deal.
> 
> I just review your pr and code, thought that your pr was not merged, if I commit my code and pr and finally merged, it will be conflicted, so I try to copy the content in your pr. Actually I do the plagiarize thing in some way.
> 
> Thanks for your explanation, I will keep reviewing the code and subscribing the seata project when I get any time.

What I am expressing is that I hope this is not plagiarism. And if you have your own implementation ideas, you should submit your own implementation instead of borrowing a lot of other people’s code

**Pull request closed without merging**
