### PR TITLE
optimize: add methods to reduce redundant code

### PR DESCRIPTION
**Pull request by Zh1Cheung**
### Ⅰ. Describe what this PR did

1. Reduced duplicate code in else branch (else statements in index> = 0 and else statements) and optimized code logic (judgment annotation.isParamInProperty () in advance) is more readable. In addition, there is still a large amount of code in this class. If else statement, this commit is only a further simplified code, but it is not optimal.
2. I think if the code is extended in this class in the future, it will become more and more difficult to maintain (the fetchContextFromObject method has too much logic and high coupling)

### Ⅱ. Does this pull request fix one issue?
xxx

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
xxx

### Ⅳ. Describe how to verify it
xxx

### CODE REVIEW

**Comment by slievrly** [comment]
@Zh1Cheung please format the code you modify，there are some code style check not passed.

**Comment by Zh1Cheung** [comment]
> 
> 
> @Zh1Cheung please format the code you modify，there are some code style check not passed.
Sorry,I encountered the same problem as #2510 , and I can't find the result.xml file he said.And it will report Non-resolvable import POM: Could not find artifact io.seata: seata-bom: pom: 1.2.0-SNAPSHOT @ io.seata: seata-parent: $ {revision}, seata \ pom.xml, line 164, column 25.I don't know how to solve it, thanks

**Comment by slievrly** [comment]
> > @Zh1Cheung please format the code you modify，there are some code style check not passed.
> > Sorry,I encountered the same problem as #2510 , and I can't find the result.xml file he said.And it will report Non-resolvable import POM: Could not find artifact io.seata: seata-bom: pom: 1.2.0-SNAPSHOT @ io.seata: seata-parent: $ {revision}, seata \ pom.xml, line 164, column 25.I don't know how to solve it, thanks

remove the first  blank line.

**Comment by diguage** [comment]
> > @Zh1Cheung please format the code you modify，there are some code style check not passed.
> > Sorry,I encountered the same problem as #2510 , and I can't find the result.xml file he said.And it will report Non-resolvable import POM: Could not find artifact io.seata: seata-bom: pom: 1.2.0-SNAPSHOT @ io.seata: seata-parent: $ {revision}, seata \ pom.xml, line 164, column 25.I don't know how to solve it, thanks

I found the XML file. It locates at `seata/compressor/seata-compressor-lz4/target/checkstyle-result.xml`. So, the XML file should be at the `/target/checkstyle-result.xml` of the module.

https://github.com/seata/seata/pull/2510#issuecomment-610169873 is my reply.

**Comment by Zh1Cheung** [comment]
> 
> 
> > > @Zh1Cheung please format the code you modify，there are some code style check not passed.
> > > Sorry,I encountered the same problem as #2510 , and I can't find the result.xml file he said.And it will report Non-resolvable import POM: Could not find artifact io.seata: seata-bom: pom: 1.2.0-SNAPSHOT @ io.seata: seata-parent: $ {revision}, seata \ pom.xml, line 164, column 25.I don't know how to solve it, thanks
> 
> remove the first blank line.

Thanks,I ran xx before (at that time my first line was not a blank line), after the build was successful, I checked the result file and found no errors, just

```
<? xml version = "1.0" encoding = "UTF-8"?>
<checkstyle version = "6.18">
</ checkstyle>
```

Later, I have not noticed this problem (the first line at this time is a blank line), I always thought it was a problem of maven dependency

In addition, I want to know if I will continue to work under this pr or create a new pr when I want to work on code optimization ?

**Comment by Zh1Cheung** [comment]
> 
> 
> > > @Zh1Cheung please format the code you modify，there are some code style check not passed.
> > > Sorry,I encountered the same problem as #2510 , and I can't find the result.xml file he said.And it will report Non-resolvable import POM: Could not find artifact io.seata: seata-bom: pom: 1.2.0-SNAPSHOT @ io.seata: seata-parent: $ {revision}, seata \ pom.xml, line 164, column 25.I don't know how to solve it, thanks
> 
> I found the XML file. It locates at `seata/compressor/seata-compressor-lz4/target/checkstyle-result.xml`. So, the XML file should be at the `/target/checkstyle-result.xml` of the module.
> 
> [#2510 (comment)](https://github.com/seata/seata/pull/2510#issuecomment-610169873) is my reply.

Thanks, I found this file later

**Pull request merged**
