### PR TITLE
bugfix: TC SkyWalking topo calling node not gather

### PR DESCRIPTION
**Pull request by zhaoyuguang**
fixed https://github.com/seata/seata/issues/3810

### CODE REVIEW

**Comment by caohdgege** [comment]
image

It seems that the newest topo is not expect. the node seata_tc & 127.0.0.1:8091 is the same node.

**Comment by zhaoyuguang** [comment]
> image
> 
> It seems the newest topo is not expect. the node seata_tc & 127.0.0.1:8091 is the same node.

If use such as Chrome, go to developer mode, copy HTTP Response, let us check the env is wrong

**Comment by caohdgege** [comment]
image

It seems ok after swtich to newest agent

**Review by caohdgege — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
