### PR TITLE
bugfix: fix the case that could not retry acquire global lock

### LINKED ISSUE #3070: Could not retry get global lock when autocommit=false
## Why you need it?
Could not retry get global lock when autocommit=false

If you want to fix it, please comment "Please assign it to me" is this issue.
## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by caohdgege**
### Ⅰ. Describe what this PR did
fix: will not retry acquire lock when LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT is true and autoCommit is false

### Ⅱ. Does this pull request fix one issue?

fixes #3070

### CODE REVIEW

**Comment by caohdgege** [comment]
image
补个图

**Comment by ggndnn** [comment]
@caohdgege I think `LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT==true` means to release local record lock before retry when global lock conflict, that was not achieved by this pr.

**Comment by caohdgege** [comment]
> @caohdgege I think `LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT==true` means to release local record lock before retry when global lock conflict, that was not achieved by this pr.

这个之前在群里跟清铭哥讨论过，在autocommit=false 的时候，进行释放本地锁有点难，然后重试策略又比较重要，暂时先通过让它不释放本地锁直接重试，后续再优化
Screenshot_20201016_203106_com alibaba android rimet

**Comment by ggndnn** [comment]
> > @caohdgege I think `LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT==true` means to release local record lock before retry when global lock conflict, that was not achieved by this pr.
> 
> 这个之前在群里跟清铭哥讨论过，在autocommit=false 的时候，进行释放本地锁有点难，然后重试策略又比较重要，暂时先通过让它不释放本地锁直接重试，后续再优化
> Screenshot_20201016_203106_com alibaba android rimet

If we have to do this, should we change the configuration meaning? Otherwise, it is easy to cause misunderstanding. By the way, how about to make use of `savepoint`?

**Comment by caohdgege** [comment]
> > > @caohdgege I think `LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT==true` means to release local record lock before retry when global lock conflict, that was not achieved by this pr.
> > 
> > 
> > 这个之前在群里跟清铭哥讨论过，在autocommit=false 的时候，进行释放本地锁有点难，然后重试策略又比较重要，暂时先通过让它不释放本地锁直接重试，后续再优化
> > Screenshot_20201016_203106_com alibaba android rimet
> 
> If we have to do this, should we change the configuration meaning? Otherwise, it is easy to cause misunderstanding. By the way, how about to make use of `savepoint`?

我个人的理解上，如果在 autocommit=false 的时候，如果要释放本地锁然后重试意味着要 **重新执行对应的DML以及业务操作** ,用savepoint或者记录到context只能保证重新执行对应的DML，没有执行对应的业务操作。现在没能找到一个方案可以实现重新执行对应的DML以及业务操作，所以才采用了这么一个临时方案。或者云嵩哥有没有什么更好的建议？
对于修改配置的定义，云嵩哥觉得改成什么好？

**Comment by ggndnn** [comment]
> > > > @caohdgege I think `LOCK_RETRY_POLICY_BRANCH_ROLLBACK_ON_CONFLICT==true` means to release local record lock before retry when global lock conflict, that was not achieved by this pr.
> > > 
> > > 
> > > 这个之前在群里跟清铭哥讨论过，在autocommit=false 的时候，进行释放本地锁有点难，然后重试策略又比较重要，暂时先通过让它不释放本地锁直接重试，后续再优化
> > > Screenshot_20201016_203106_com alibaba android rimet
> > 
> > 
> > If we have to do this, should we change the configuration meaning? Otherwise, it is easy to cause misunderstanding. By the way, how about to make use of `savepoint`?
> 
> 我个人的理解上，如果在 autocommit=false 的时候，如果要释放本地锁然后重试意味着要 **重新执行对应的DML以及业务操作** ,用savepoint或者记录到context只能保证重新执行对应的DML，没有执行对应的业务操作。现在没能找到一个方案可以实现重新执行对应的DML以及业务操作，所以才采用了这么一个临时方案。或者云嵩哥有没有什么更好的建议？
> 对于修改配置的定义，云嵩哥觉得改成什么好？

I think **biz op** is something bigger than things here, the global lock keys are also from dml and db values, we can consider this configuration only in at mode so far. Under this consideration, what about `savepoint`?
As for the configuration naming, let's think about it together, maybe more discussions. When the configuration changed, the code logic may have to be changed.

**Review by slievrly — APPROVED** [review]
LGTM, the retry functionality is fine, but the meaning of the configuration item has changed and may require further consideration.

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
