### PR TITLE
bugfix: fix can not get update columns with database name

### LINKED ISSUE #3395: buildAfterImageSQL时，如果更新语句的字段是库名加上表名字段getUpdateColumns获取不到更新字段
buildAfterImageSQL时，如果数据库链接是全称getUpdateColumns获取不到更新字段。
如果数据库链接，如update seata.test.info，其中seata为库名字，test是表名，
@Override
    public List<String> getUpdateColumns() {
        List<SQLUpdateSetItem> updateSetItems = ast.getItems();
        List<String> list = new ArrayList<>(updateSetItems.size());
        for (SQLUpdateSetItem updateSetItem : updateSetItems) {
            SQLExpr expr = updateSetItem.getColumn();
            if (expr instanceof SQLIdentifierExpr) {
                list.add(((SQLIdentifierExpr)expr).getName());
            } else if (expr instanceof SQLPropertyExpr) {
                // 这里拿出来的owner是seata.test，会把它当作SQLPropertyExpr
                SQLExpr owner = ((SQLPropertyExpr)expr).getOwner();
                if (owner instanceof SQLIdentifierExpr) {
                    list.add(((SQLIdentifierExpr)owner).getName() + "." + ((SQLPropertyExpr)expr).getName());
                }
            } else {
                throw new SQLParsingException("Unknown SQLExpr: " + expr.getClass() + " " + expr);
            }
        }
        return list;
    }

如果更新语句为： update seata.test set seata.test.info = "test" where seata.test.id = 1，则getUpdateColumns返回值是一个空的list

### PR DESCRIPTION
**Pull request by sustly**
### Ⅰ. Describe what this PR did
buildAfterImageSQL时，如果数据库链接是全称getUpdateColumns获取不到更新字段。
如果数据库链接，如update seata.test.info，其中seata为库名字，test是表名，如果更新语句为： update seata.test set seata.test.info = "test" where seata.test.id = 1，则getUpdateColumns返回值是一个空的list.
支持了更新如果是库名+表名+字段的sql
### Ⅱ. Does this pull request fix one issue?

fixes #3395 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
没有

### Ⅳ. Describe how to verify it
1.4.1版本写库名，测试不通过，获取不了更新字段
image
fixes bug后，测试通过
image

### Ⅴ. Special notes for reviews
没有

### CODE REVIEW

**Comment by sustly** [comment]
Can my pull request be merged?

**Comment by slievrly** [comment]
> Can my pull request be merged?If not, please fix this bug.

did Oracle and PostgresQL do actual testing?

**Comment by sustly** [comment]
> > Can my pull request be merged?If not, please fix this bug.
> 
> did Oracle and PostgresQL do actual testing?
I do not have Oraclee and PostgresQL environment.

**Comment by sustly** [comment]
> > > Can my pull request be merged?If not, please fix this bug.
> > 
> > 
> > did Oracle and PostgresQL do actual testing?
> > I do not have Oracle and PostgresQL environment.
But in the test I did not find any problems

**Review by l81893521 — APPROVED** [review]
LGTM. Mysql And Oracle test passed, pgsql do not have this problem. You can remove the code in pgsql or not.

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
