### PR TITLE
[release] release for 1.6.0

### PR DESCRIPTION
**Pull request by slievrly**
Signed-off-by: slievrly <slievrly@163.com>

- [x] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

vote for release 1.6.0(https://github.com/seata/seata/milestone/23)

at least 3 votes with binding to pass

Please vote accordingly:
- [x] +1 approve
- [x] +0 no opinion
- [x] -1 disapprove with the reason

vote result:  vote passed

+5 binding

[a364176773](https://github.com/a364176773)
[xingfudeshi](https://github.com/xingfudeshi)
[l81893521](https://github.com/l81893521)
[caohdgege](https://github.com/caohdgege)
[slievrly](https://github.com/slievrly)

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
+1 approve
test case：
http tm -> at-rm ->xa rm  success
at case insert , update

**Review by xingfudeshi — APPROVED** [review]
+1 Approve
UPDATA JOIN testing passed.
UPDATA JOIN doc added.
Server-side multi-registry exposure testing passed.

**Comment by renliangyu857** [comment]
+1 Approve
XA phase two testing in 8.0.30 and 5.7 version passed

**Review by l81893521 — APPROVED** [review]
+1 approve
test case

mysql 8.0.28-arm64 insert
```
// auto increment
jdbcTemplate.update("insert into account_tbl(USER_ID, money, information, create_time) values (?, ?, ?, now())", UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?)", money, "hello world".getBytes(), UUID.randomUUID().toString());
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information) values (null, ?, ?, ?)", UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into `account_tbl`(user_id, money, information) values (?, ?, ?)", UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into seata_client.account_tbl(user_id, money, information) values (?, ?, ?)", UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into seata_client.`account_tbl`(user_id, money, information) values (?, ?, ?)", UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into `seata_client`.`account_tbl`(user_id, money, information) values (?, ?, ?)", UUID.randomUUID().toString(), money, "hello world".getBytes());
// insert primary key
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())", UUIDGenerator.generateUUID(), UUID.randomUUID().toString(), money, "hello world".getBytes());
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information) values (?, ?, ?, ?)", UUIDGenerator.generateUUID(), UUID.randomUUID().toString(), money, "hello world".getBytes());
// multi pk
jdbcTemplate.update("insert into account_tbl_multi_pk(user_id, sex, money) values (?, ?, ?)", UUID.randomUUID().toString(), 1, money);
jdbcTemplate.update("insert into account_tbl_multi_pk(USER_ID, sex, money) values (?, ?, ?)", UUID.randomUUID().toString(), 1, money);
//batch
jdbcTemplate.update("insert into account_tbl(money, create_time, information, user_id) values (?, now(), ?, ?), (?, now(), ?, ?)",
        money, "hello world".getBytes(), UUID.randomUUID().toString(),
        money, "hello world".getBytes(), UUID.randomUUID().toString());
jdbcTemplate.update("insert into account_tbl(money, create_time, information, user_id, id) values (?, now(), ?, ?, ?), (?, now(), ?, ?, ?)",
        money, "hello world".getBytes(), UUID.randomUUID().toString(), UUIDGenerator.generateUUID(),
        money, "hello world".getBytes(), UUID.randomUUID().toString(), UUIDGenerator.generateUUID());
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?), (now(), ?, ?, ?)",
        money, "hello world".getBytes(), UUID.randomUUID().toString(),
        money, "hello world".getBytes(), UUID.randomUUID().toString());
jdbcTemplate.update("insert into account_tbl(create_time, money, information, user_id, id) values (now(), ?, ?, ?, ?), (now(), ?, ?, ?, ?)",
        money, "hello world".getBytes(), UUID.randomUUID().toString(), UUIDGenerator.generateUUID(),
        money, "hello world".getBytes(), UUID.randomUUID().toString(), UUIDGenerator.generateUUID());
jdbcTemplate.batchUpdate("insert into account_tbl(create_time, money, information, user_id) values (now(), ?, ?, ?)", new BatchPreparedStatementSetter() {
    @Override
    public void setValues(PreparedStatement ps, int i) throws SQLException {
        ps.setInt(1, money);
        ps.setBytes(2, "hello world".getBytes());
        ps.setString(3, UUID.randomUUID().toString());
    }

    @Override
    public int getBatchSize() {
        return 2;
    }
});
```

mysql 8.0.28-arm64 update
```
jdbcTemplate.update("update account_tbl set money = money - ?, sex = 1 where user_id = ?", money, userId);
jdbcTemplate.update("update `account_tbl` set money = money - ? where user_id = ?", money, userId);
jdbcTemplate.update("update seata_client.account_tbl set money = money - ? where user_id = ?", money, userId);
jdbcTemplate.update("update seata_client.`account_tbl` set money = money - ? where user_id = ?", money, userId);
//in
jdbcTemplate.update("update account_tbl set money = money - ? where user_id in (?)", money, userId);
//between
jdbcTemplate.update("update account_tbl set money = money - ? where user_id between ? and ?", money, userId, userId);
//exist
jdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where exists (select 'U100002' as user_id from dual)", money);

//not exist
jdbcTemplate.update("update account_tbl a set money = money - ? "
        + "where not exists (select 'U100003' as user_id from dual)", money);

//multi pk
jdbcTemplate.update("update account_tbl_multi_pk set money = money - ?, sex = 1 where user_id = ?", money, userId);
```

mysql 8.0.28-arm64 delete
```
Long id = UUIDGenerator.generateUUID();
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ?", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from `account_tbl` where id = ?", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from seata_client.account_tbl where id = ?", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from seata_client.`account_tbl` where id = ?", id);

//order by
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? order by user_id", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? order by user_id desc", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? order by user_id asc", id);

//limit
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? limit 1", id);

//order by + limit
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? order by user_id limit 1", id);

jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id = ? order by user_id desc limit 1", id);

//in
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id in (?)", id);

//between
jdbcTemplate.update("insert into account_tbl(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl where id between ? and ?", id, id);

//multi pk
jdbcTemplate.update("insert into account_tbl_multi_pk(id, user_id, money, information, create_time) values (?, ?, ?, ?, now())",
        id, UUID.randomUUID().toString(), 999, "hello world".getBytes());
jdbcTemplate.update("delete from account_tbl_multi_pk where id = ?", id);
```

**Review by caohdgege — APPROVED** [review]
+1 approve
test case：
1. normal insert，update，delete condition in `at mode`
2. insert into on duplicate key update case
3. update join

**Comment by slievrly** [comment]
+1 binding

**Pull request merged**
