### PR TITLE
optimize: optimize the error of join table syntax

### PR DESCRIPTION
**Pull request by l81893521**
### Ⅱ. Does this pull request fix one issue?
#2442

### CODE REVIEW

**Comment by caohdgege** [comment]
Is there nessnary to modify  the method `getTableAlias`？
plz modify the title.

**Review by a364176773 — APPROVED** [review]
LGTM

**Review by caohdgege — APPROVED** [review]
LGTM

**Comment by l81893521** [comment]
> Is there nessnary to modify the method `getTableAlias`？
> plz modify the title.

Maybe change it when support join sql.

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
