### PR TITLE
optimize: optimize sqlType actuator based on static factory pattern

### PR DESCRIPTION
**Pull request by pengzhengfa**

### CODE REVIEW

**Comment by pengzhengfa** [comment]
@lightClouds917 @a364176773 @l81893521  Hello, the code has been revised. Please review it

**Comment by a364176773** [comment]
你好,其实你无需重新开一个pr,仅需把你更改好的代码按照p3c代码规范,本地打包能通过,提交到你对应的分支仓库即可然后关联这个仓库的pr会更新新的代码,无需每一个都去重新做提交.

**Comment by pengzhengfa** [comment]
@a364176773 OK, thank you. I'll pay attention next time

**Comment by slievrly** [comment]
@pengzhengfa code review approved, but this branch is out  of date,  please merge with upstream/develop and push it.

**Comment by pengzhengfa** [comment]
@slievrly  Hello, I don't have push permission. I've tried many times. I don't know whether it's my operation or the permission

**Comment by pengzhengfa** [comment]
@slievrly  Hello, there seems to be a little problem in GitHub warehouse. I have submitted a new request. Please check it. Thank you

**Pull request closed without merging**
