### PR TITLE
optimize: add copyright notice

### LINKED ISSUE #4799: the notice file is empty
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

the notice file is empty

### PR DESCRIPTION
**Pull request by AlexStocks**
- [ ] I have registered the PR [changes](https://github.com/seata/seata/tree/develop/changes).

### Ⅰ. Describe what this PR did

add apache notice

### Ⅱ. Does this pull request fix one issue?

fixes #4799

### CODE REVIEW

**Comment by slievrly** [comment]
Pls add change log in:
https://github.com/seata/seata/blob/develop/changes/en-us/develop.md
https://github.com/seata/seata/blob/develop/changes/zh-cn/develop.md

**Comment by AlexStocks** [comment]
> Pls add change log in: https://github.com/seata/seata/blob/develop/changes/en-us/develop.md https://github.com/seata/seata/blob/develop/changes/zh-cn/develop.md

done

**Comment by slievrly** [comment]
> > Pls add change log in: https://github.com/seata/seata/blob/develop/changes/en-us/develop.md https://github.com/seata/seata/blob/develop/changes/zh-cn/develop.md
> 
> done

The change log should be moved to the `optimize` module in develop.md . `bugfix` represents a fix to transaction service.

**Review by a364176773 — APPROVED** [review]
LGTM @slievrly PTAL

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
