### PR TITLE
optimize: consul supports ACL token

### PR DESCRIPTION
**Pull request by jiehai**
### Ⅰ. Describe what this PR did
在使用consul做为注册配置中心时，增加seata对 ACL token的支持

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
对seata服务端和客户端进行配置启动即可验证

### Ⅳ. Describe how to verify it
启用consul的acl，给seata分配一个有足够权限的token，并配置到服务端配置和客户端的配置文件中，做好以上配置后启动程序，看是否能够正常注册和读取配置

### CODE REVIEW

**Comment by a364176773** [comment]
https://github.com/seata/seata/blob/develop/CONTRIBUTING.md 可以阅读下这边得手册,比如 code style

**Comment by jiehai** [comment]
已将tab替换为4个空格

**Comment by slievrly** [comment]
@jiehai 
image

**Comment by a364176773** [comment]
please resolve code conflicts

**Comment by slievrly** [comment]
image

**Comment by a364176773** [comment]
麻烦解决下冲突，server的resources文件夹下的registy.conf和script文件夹下的server中的conf及client中的spring和conf的内容需要补充

**Comment by l81893521** [comment]
I will close this pr because seata already support acl token in consul. Waiting for you next contribution, thanks you.

**Pull request closed without merging**
