### PR TITLE
bugfix: remove next line to space

### LINKED ISSUE #3164: SQL的where条件中在构建查询beforeImage时，包含 "\n" 会被替换成 " "
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
SQL的where条件中在构建查询beforeImage时，包含 "\n" 会被替换成 " "
以及根据代码中的备注，说明是由于druid的bug，具体指的是？@81519434 

image
image
image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- OS :
- Others:

### PR DESCRIPTION
**Pull request by caohdgege**
### Ⅰ. Describe what this PR did
fix build image wrong when where condition contains "\n"

### Ⅱ. Does this pull request fix one issue?

fixes #3164

### CODE REVIEW

**Review by a364176773 — APPROVED** [review]
LGTM

**Comment by caohdgege** [comment]
@81519434 文俊哥有空也看一下这个pr

**Comment by 81519434** [comment]
LGTM

**Review by jsbxyyx — APPROVED** [review]
LGTM for @81519434

**Pull request merged**
