### PR TITLE
Tidy the dependency

### PR DESCRIPTION
**Pull request by lovepoem**
### Ⅰ. Describe what this PR did

tidy the maven dependency

### Ⅱ. Does this pull request fix one issue?
https://github.com/seata/seata/issues/933

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Config change 

### Ⅳ. Describe how to verify it

ci pass
### Ⅴ. Special notes for reviews

1、Unify the version of `netty`  
2、Remove guava ，use [caffine](https://github.com/ben-manes/caffeine) to replace guava cache
3、Remove other useless jars
4、Upgrade junit4 to [junit5](https://junit.org/junit5/docs/current/user-guide)
5、Remove testng (use  [junit5](https://junit.org/junit5/docs/current/user-guide) )

### CODE REVIEW

**Comment by hongweiyi** [comment]
Suggestion:

1. make commons-pool2(just for redis) provided?
2. upgrade FastJSON to 1.2.50, 1.2.48 has security issue

**Comment by lovepoem** [comment]
> Suggestion:

make commons-pool2(just for redis) provided?
upgrade FastJSON to 1.2.50, 1.2.48 has security issue

Done in https://github.com/seata/seata/pull/981/commits/a9a09cecf8bd0030c9bd3dea6514c446eb819817

**Comment by lovepoem** [comment]
> there are some conflict files.

fixed

**Comment by lovepoem** [comment]
> great job，but I have some confusion，why delete seata-* in dependencyManagement， and each module has a <version>${project.version}</version> in other pom?

I think the version of dependecies we put in the dependencyManagement is changeable， but the version of submodule dependency is fixed, we can use `${project.version}` , so  I think there is a little redundancy to put all submodules in the seata/pom.xml

**Pull request merged**
