### PR TITLE
feature: support trace the transaction link according to the XID

### LINKED ISSUE #5599: how to trace the transaction link according to the XID
## Why you need it?
I want to implement the distributed transaction tracing according to the XID, but  seata-plugin could not finish it.

## How it could be?
Intercept distributed transaction requests with xid and span xid into the seata-plugin

## Other related information
End-to-end distributed transaction tracing

### PR DESCRIPTION
**Pull request by vonfun**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
support trace the transaction link according to the XID

### Ⅱ. Does this pull request fix one issue?

fixes #5599

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

Original test cases can be do
### Ⅳ. Describe how to verify it
use skywalking agent verify it

### Ⅴ. Special notes for reviews
no

### CODE REVIEW

**Comment by vonfun** [comment]
license check is not available，how to deal it

**Comment by a364176773** [comment]
> license check is not available，how to deal it

Don't worry about that

**Comment by vonfun** [comment]
> > license check is not available，how to deal it
> 
> Don't worry about that

>I want to still finish pull request, what should I do ?

**Review by slievrly — APPROVED** [review]
LGTM

**Comment by slievrly** [comment]
@vonfun thanks for your contributions.

**Pull request merged**
