### PR TITLE
Refactor : Server (This needs to be divided into several parts)

### PR DESCRIPTION
**Pull request by ph3636**
### Ⅰ. Describe what this PR did
Refactor : Server

### CODE REVIEW

**Comment by lzf971107** [comment]
@ph3636 

[ERROR] Errors: 
[ERROR]   DefaultCoordinatorMetricsTest.test:44 » NullPointer
[ERROR]   DefaultCoordinatorTest.beforeClass:79 » NullPointer
[ERROR]   DefaultCoreTest.initSessionManager:76 » NullPointer
[ERROR]   DefaultCoreForEventBusTest.test:59 » NullPointer
[ERROR]   SessionHolderTest.testInit:52 » NullPointer
[ERROR]   SessionStoreTest.testRestoredFromFile:129 » NullPointer
[ERROR]   SessionStoreTest.testRestoredFromFileAsyncCommitting:206 » NullPointer
[ERROR]   SessionStoreTest.testRestoredFromFileCommitRetry:266 » NullPointer
[ERROR]   SessionStoreTest.testRestoredFromFileRollbackFailed:378 » NullPointer
[ERROR]   SessionStoreTest.testRestoredFromFileRollbackRetry:327 » NullPointer

Fix the unit test exception, or you won't pass the ci check

**Comment by ph3636** [comment]
thanks, I know. I'm a little busy now. @lzf971107

**Comment by lzf971107** [comment]
> thanks, I know. I'm a little busy now. @lzf971107

Oops, sorry to bother you

**Comment by ph3636** [comment]
Thank you for reminding me. @lzf971107

**Comment by ph3636** [comment]
> > thanks, I know. I'm a little busy now. @lzf971107
> 
> Oops, sorry to bother you

**Comment by xingfudeshi** [comment]
@ph3636 Please resolve conflicting files.

**Comment by ph3636** [comment]
> @ph3636 Please resolve conflicting files.

This needs to be divided into several parts. At present, one has been disassembled.https://github.com/seata/seata/pull/2134

**Comment by slievrly** [comment]
temporarily closed due to duplication.

**Pull request closed without merging**
